### ISSUE TITLE
Periodic square mesh produces a warning about DQ element

### ISSUE THREAD

**Issue by robertsawko** [firedrakeproject/firedrake#1090]
I am setting up a case on square quadrilateral mesh. It's a simple Poisson equation but my target test case is meant be periodic in the x direction so I went with `PeriodicSquareMesh` object from `utility_meshes`.
```python
mesh = PeriodicSquareMesh(N, N, 1.0, direction='x', quadrilateral=True)
```

The strange thing is that no matter which element I am trying in `FunctionSpace`:
```python
V = FunctionSpace(mesh, 'Q', 2)
# V = FunctionSpace(mesh, 'DQ', 2)
# V = FunctionSpace(mesh, 'CG', 2)
```
Firedrake produces the following warning
```
UFL:WARNING Discontinuous Lagrange element requested on quadrilateral, creating DQ element
```
It produced two additional warnings if I decide to save my solution.

The problem disappears if I use quadrilateral `UnitSquareMesh`.

**Comment by wence-** [comment]
This is because when we make the coordinate field we say `VectorFunctionSpace(mesh, "DG", 1)`.  But there are two discontinuous spaces on quadrilaterals, `DQ` (which is what you get) and the discontinuous serendipity space (not implemented).

To squelch this, we should pick the correct element name based on the cell.
