### ISSUE TITLE
installation trouble on Sierra

### ISSUE THREAD

**Issue by krlong014** [firedrakeproject/firedrake#1124]
Fails during petsc installation. 

Output attached here:
[try.txt](https://github.com/firedrakeproject/firedrake/files/1195105/try.txt)
.
Install log attached here:
[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/1195108/firedrake-install.log.txt)

**Comment by dham** [comment]
Hi Kevin,

I think you're hitting a known issue with SSL and the python.org Mac binary installer. Apparently SSL doesn't work out of the box in that installation and you have to run the following command to activate it:
```
open "/Applications/Python 3.6/ReadMe.rtf"
```
for more details https://bugs.python.org/issue29065

There is no reason I know of why installing with that Python wouldn't then work, though it's not the route that the Firedrake developers use. We install Python 3 using homebrew, which does not appear to have this issue:
```
brew install python3
```

**Comment by wence-** [comment]
Hi Kevin,

As David points out, this appears to be a known issue.  His provided command will open the README that tells you what to do (that in itself won't fix the problem).

To test that it worked (without running firedrake-install from scratch and failing again) you can then run:

```
python3 -c 'import urllib.request; urllib.request.urlretrieve("https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz")'
```

This should succeed.

I also notice from the output of `firedrake-install` that you probably have both homebrew and macports installed:

```
PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin//opt/local/bin:/opt/local/sbin:/anaconda/bin:/anaconda:/Users/kevin/Code/zeno/bin:/usr/local/gcc-4.9.3/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin
```

(Macports puts binaries in `/opt/local/bin` and `/opt/local/sbin`).

I recommend that, for the purposes of running firedrake, you sanitise your path so that macports binaries are not visible.  The reason for this is that they ship an assembler which is incompatible with the object files that are generated by the system compilers: in particular we install MPI via homebrew, for which the compiler wrappers use the system compilers.

**Comment by krlong014** [comment]
David & Lawrence, 

Thanks! I removed macports, removed the old python installation, got python from homebrew, and proceeded. That fixed the problem. 

However, another error arose downstream. Here's the log file: 
[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/1199282/firedrake-install.log.txt)

**Comment by wence-** [comment]
Hi Kevin,

this looks like more incompatibility between the assembly that GCC generates and what the system (clang-based) assembler is expecting.

I see from the log you have:

```
        --with-cc=/usr/local/gcc-4.9.3/bin/mpicc
        --with-cxx=/usr/local/gcc-4.9.3/bin/mpicxx
        --with-fc=/usr/local/gcc-4.9.3/bin/mpif90
```

Which is not a homebrew provided MPI I think.

Looking at the environment output:

```
PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/local/bin:
/opt/local/sbin:/usr/local/bin//opt/local/bin:/opt/local/sbin:/anaconda/bin:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# There should be a colon after /usr/local/bin here.
/anaconda:/Users/kevin/Code/zeno/bin:/usr/local/gcc-4.9.3/bin:
/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:
/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:
/Library/TeX/texbin
```

So it seems that you're using an installation of the MPI compiler that compiles with gcc.  But gcc-4.9 emits code that can't be assembled by the system (clang-based) assembler (e.g. see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64540), and indeed the error message from building HDF5 via PETSc is exactly equivalent:

```
error: ambiguous instructions require an explicit suffix (could be 'fisttps', or 'fisttpl')
            fisttp  (%rbx)
```

So hopefully if you sanitise your path a little more, you can ensure that you're using homebrew (or apple) provided compilers everywhere.

A simple test:

```
cat > test.c << EOF
int main()
{
  unsigned char a = 0;
  long double d = 0.0;

  d = (long double)a;

  return 0;
}
EOF
mpicc -Wa,-q test.c -o test
```

Should succeed and produce a `test` binary.  I think you will find with your current environment that it does not (producing an error similar to the one above).

**Comment by krlong014** [comment]
Ok, I took care of that and a couple of similar issues downstream. Currently it's failing during the installation of libspatialindex. Log file is attached. 
[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/1201898/firedrake-install.txt)

A couple of comments: 

(1) you'll notice options such as -L/Users/kevin/Code/Compilers/gcc-4.9.3/BUILD/x86_64-apple-darwin15.5.0/libstdc++-v3/src/.libs in the final gcc invocation. I've deleted those directories (which explains the various missing directory warnings) and am not sure why they're in the search path. Not sure if this is relevant to the problem, but it suggest something is off in my setup if your script is searching in a nonexistent directory. 

(2) If I don't wipe out the firedrake directory from a previous attempt I get the message
"Specified venv '/Users/kevin/Code/firedrake' already exists
Can't install into existing venv '/Users/kevin/Code/firedrake'"
It soaks up a lot of time rebuilding petsc, etc, to diagnose and fix a later problem. Is there a way to resume an interrupted installation after fixing a problem, rather than starting from scratch?

(3) I see there's the --honour-petsc-dir option that would let me build against my own petsc installation. But what about the other dependencies such as exodus, netcdf, etc? Does --honour-petsc-dir also bypass building those, and would I put these in the same directory as my petsc installation? (I have those installed as part of a Trilinos build, but could move things around)

Thanks for all your help.

**Comment by krlong014** [comment]
Btw, after cleaning up my path, "mpicc -Wa,-q test.c -o test" fails with the error 
clang: error: unsupported argument '-q' to option 'Wa,'

**Comment by miklos1** [comment]
> (3) I see there's the --honour-petsc-dir option that would let me build against my own petsc installation.

**Comment by miklos1** [comment]
> (3) I see there's the --honour-petsc-dir option that would let me build against my own petsc installation.

With `--honour-petsc-dir` it is your responsibility to provide a PETSc build that is suitable for Firedrake. For that, you need to pay attention to the following:
- The PETSc version: You should grab the `firedrake` branch of https://github.com/firedrakeproject/petsc. Release versions of PETSc are too old for Firedrake, and `master` sadly breaks too often. The `firedrake` branch points to version that is known to work with Firedrake, and is somewhat regularly updated to `master`.
- Further external dependencies. `firedrake-install` tells you what options it gives to PETSc `configure` if you specify `--show-petsc-configure-options`. Make sure to specify all those in your manual PETSc build so that all Firedrake dependencies will be present.

**Comment by miklos1** [comment]
> It soaks up a lot of time rebuilding petsc, etc, to diagnose and fix a later problem. Is there a way to resume an interrupted installation after fixing a problem, rather than starting from scratch?

Unfortunately, there isn't.

**Comment by miklos1** [comment]
Ok, so this line and what follows looks quite dodgy:
> /bin/sh ./libtool  --tag=CC   --mode=link gcc  -Wall -Wno-long-long -pedantic  -version-info 4:2:0 -no-undefined -lstdc++  -o libspatialindex.la -rpath /Users/kevin/Code/firedrake/lib  src/spatialindex/liblibrary.la src/storagemanager/libstoragemanager.la src/rtree/librtree.la src/mvrtree/libmvrtree.la src/tprtree/libtprtree.la src/tools/libtools.la -lpthread
libtool: link: gcc -dynamiclib  -o .libs/libspatialindex.4.dylib   -Wl,-force_load,src/spatialindex/.libs/liblibrary.a -Wl,-force_load,src/storagemanager/.libs/libstoragemanager.a -Wl,-force_load,src/rtree/.libs/librtree.a -Wl,-force_load,src/mvrtree/.libs/libmvrtree.a -Wl,-force_load,src/tprtree/.libs/libtprtree.a -Wl,-force_load,src/tools/.libs/libtools.a  /usr/local/lib/libstdc++.dylib -L/Users/kevin/Code/Compilers/gcc-4.9.3/BUILD/x86_64-apple-darwin15.5.0/libstdc++-v3/src -L/Users/kevin/Code/Compilers/gcc-4.9.3/BUILD/x86_64-apple-darwin15.5.0/libstdc++-v3/src/.libs -L/Users/kevin/Code/Compilers/gcc-4.9.3/BUILD/x86_64-apple-darwin15.5.0/libstdc++-v3/libsupc++/.libs -lm -lpthread    -install_name  /Users/kevin/Code/firedrake/lib/libspatialindex.4.dylib -compatibility_version 5 -current_version 5.2 -Wl,-single_module

So this calls to C (not C++ linker) but attempts to link in the C++ standard library from the specified paths, which point to directories that you have deleted. So unsurprisingly, it fails to find the libraries, and consequently linking fails due to missing symbols.

This looks like your compiler/linker/etc. situation is still messed up. You path seems OK, can you try

    $ brew doctor

and if it suggests something, do so. Moreover, what is the output of

    $ alias
    $ which gcc
    $ which g++
    $ which ld
    $ which mpicc

**Comment by krlong014** [comment]
Ok, so I blew away everything in /usr/local, blew away the homebrew cache, and re-installed homebrew from scratch, installed python from homebrew. After that, firedrake installed without a hitch. 

"make alltest" reported one failure and 22 xfails. Here's the failure message:

`>============================================================== FAILURES ==============================================================
______________________________________________________ test_all_dofs_on_facets _______________________________________________________

    def test_all_dofs_on_facets():
        mesh = UnitSquareMesh(5, 5)
        V_elt = FiniteElement("BDM", triangle, 1)
        # BDM has all dofs on facets, so these should be the same
        W1_elt = FacetElement(V_elt)
        V = FunctionSpace(mesh, V_elt)
        W1 = FunctionSpace(mesh, W1_elt)
        f = Function(V).assign(1)
        g = Function(W1).assign(1)
        n = FacetNormal(mesh)
    
>       assert abs(assemble(dot(f, f)*dx) - assemble(dot(g, g)*dx)) < 1e-13
E       AssertionError: assert 1.0658141036401503e-13 < 1e-13
E        +  where 1.0658141036401503e-13 = abs((58.333333333333464 - 58.333333333333357))
E        +    where 58.333333333333464 = assemble((Dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x13d599898>, FiniteElement('Brezzi-...-Marini', triangle, 1), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 23578)), 49952)) * dx))
E        +      where Dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x13d599898>, FiniteElement('Brezzi-...-Marini', triangle, 1), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 23578)), 49952)) = dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x13d599898>, FiniteElement('Brezzi-Douglas-Marini', triangle, 1), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 23578)), 49952), Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x13d599898>, FiniteElement('Brezzi-Douglas-Marini', triangle, 1), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 23578)), 49952))
E        +    and   58.333333333333357 = assemble((Dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x13d599898>, RestrictedElement(Fini...triangle, 1), 'facet'), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 23578)), 49957)) * dx))
E        +      where Dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x13d599898>, RestrictedElement(Fini...triangle, 1), 'facet'), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 23578)), 49957)) = dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x13d599898>, RestrictedElement(FiniteEl... triangle, 1), 'facet'), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 23578)), 49957), Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at 0x13d599898>, RestrictedElement(FiniteEl... triangle, 1), 'facet'), name=None), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 23578)), 49957))

tests/regression/test_facet_elements.py:16: AssertionError
================================= 1 failed, 4349 passed, 125 skipped, 22 xfailed in 3290.69 seconds ==================================
`

**Comment by miklos1** [comment]
`AssertionError: assert 1.0658141036401503e-13 < 1e-13` this is fine I guess. "xfail" means expected failure, so they are fine too. I consider this a success.
