### ISSUE TITLE
Hybridization preconditioner probably unsafe with mesh movement

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#1140]
As discussed with @thomasgibson, the H(div) projection probably assembles and saves a matrix.  This will need updating if the mesh changes (in an LVP/LVS, one could tie this to `constant_jacobian`, but not sure how to do this for a nonlinear problem).

Of course, this only matters for L^2 projection... the new averaging-projection should do the right thing since it just works on DoF values.

**Comment by thomasgibson** [comment]
I've rebased the `reconstructor` branch on master. Try checking out that branch and replace
```python
'hdiv_projection': {'ksp_type': 'cg',
                    'ksp_rtol': 1e-8}
```
with
```python
'hdiv_projection': {'method': 'average'}
```
in the SW parameters. This will at least verify that the averaging-projection DTRT.

**Comment by thomasgibson** [comment]
So upon further investigating, I think the problem is related to the inversion of the HDiv mass matrix to construct the "broken residual." I think the `update` method in the `HybridizationPC` class needs to somehow know when to reconstruct the HDiv mass matrix. @wence-, does that sound accurate?

**Comment by wence-** [comment]
The update method is called whenever the jacobian or preconditioning matrix changes.  You can update things in there.  But you presumably don't need to reassemble the mass matrix that often, only when the mesh moves.  I don't know how best to indicate that.

**Comment by wence-** [comment]
A safe thing to do is to reassemble the mass matrix in `update`.  In particular, I think you need to reassemble both the mass matrix from hdiv_projection_ksp and the one from hdiv_mass_ksp.

This is conservative in that if you use the preconditioner inside a newton iteration, these matrices will be rebuilt every new iteration (also the case for the trace operator, but I think that's right).  But the mesh movement stuff is sort of bad because it's this complete action at a distance.

I wonder if the right thing to do is to call `SNESReset` when the mesh moves, and require you to implement `reset(self, pc)` in your PC.

**Comment by thomasgibson** [comment]
Is this still a problem? The `HybridizationPC` no longer builds a mass matrix to perform projections.

**Comment by wence-** [comment]
I don't think it is.
