### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by emalit1** [firedrakeproject/firedrake#1193]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/1734452/firedrake-install.log)

**Comment by emalit1** [comment]
background: I'm using the bash emulator on Windows 10 to try installing this. I barely know anything about linux.

**Comment by wence-** [comment]
At the end of the install, there is this:

```
2018-02-18 00:24:05,618 INFO     installed.
2018-02-18 00:24:05,620 WARNING Specified venv '/mnt/c/a/firedrake' already exists
2018-02-18 00:24:05,621 ERROR  Can't install into existing venv '/mnt/c/a/firedrake'
2018-02-18 00:24:05,622 INFO   
```

So it looks like you ran the installation script in a directory `/mnt/c/a`.  It wants to make a directory called `firedrake` in the directory you run it from.  But there was already a directory (or file?) named firedrake in the way.  The installation aborted so as not to overwrite any files.

If you don't care about the `/mnt/c/a/firedrake` directory, you can remove it and try again.

Otherwise, you'll have to use a different directory.

**Comment by sharma-kk** [comment]
Hi, 
I am also facing the same issue. I tried installing in a different directory, but i am seeing the same error again.
Kindly help.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6257642/firedrake-install.log)
