### ISSUE TITLE
Manual trace projection

### ISSUE THREAD

**Issue by andreasbock** [firedrakeproject/firedrake#1198]
Given a `CG1` field `b`, I would like to do a manual projection of `dot(b, n)` onto a linear `Discontinuous Lagrange Trace` (`DGT1`) space (script include below) to detect on which edges this expression vanishes. Since the degrees of freedom for `DGT1` correspond to those for `BDM1`, I have been using the built-in `project` method for the latter space up until now. I am trying to understand why these two projections are providing very dissimilar values (up to a factor of edge length). In particular, the manual trace projection is not giving me values of `dot(b, n)` that I recognise. The script below computes both projections for a piece-wise constant `b` and shows the differences:

**MWE:**
```
from firedrake import *
import numpy as np

# mesh & fs
res = 3
mesh = UnitSquareMesh(res, res)
DGT = FunctionSpace(mesh, "DGT", 1)
CG = FunctionSpace(mesh, "CG", 1)

# construct rhs
vl_exp = Expression("x[1]<0.3 || 0.7<x[1] ? 1 : 0")
b = as_vector((Function(CG).interpolate(vl_exp), 1))

# Method 1: manual projection of b.n onto trace function `w1`
u, v = TrialFunction(DGT), TestFunction(DGT)
w1 = Function(DGT)

bbc = DirichletBC(DGT, 0, "on_boundary")
n = FacetNormal(mesh)
solve(u('+')*v('+')*dS == dot(b, n)('+')*v('+')*dS, w1, bcs=bbc)

# Method 2: Compute the BDM1 projection `w2`
BDM = FunctionSpace(mesh, "BDM", 1)
w2 = project(b, BDM)
File("w2.pvd").write(w2)  # visualise to see the strip where `w2` is zero

print("w1 = ", w1.dat.data, "\n")
print("w2 = ", w2.dat.data, "\n")

# Number of zero entries in w{1,2}:
tol = 1e-04
switch1 = Function(DGT).assign(conditional(abs(w1)<tol, 1, 0))

zero_nodes1 = np.unique(np.where(switch1.dat.data_ro_with_halos>tol)[0])
zero_nodes2 = np.unique(np.where(abs(w2.dat.data_ro_with_halos)<tol)[0])

print("zero_nodes1 = ", zero_nodes1, "\n")
print("zero_nodes2 = ", zero_nodes2, "\n")
print("Equal? : ", zero_nodes1 == zero_nodes2)
```

`firedrake-status`:
```
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|COFFEE              |master                        |5bb1b30   |False     |
|FInAT               |master                        |ef12759   |False     |
|PyOP2               |master                        |8a918cfc  |False     |
|fiat                |master                        |4a201c7   |False     |
|firedrake           |master                        |743c20dc  |False     |
|h5py                |firedrake                     |c1e4a81   |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|petsc               |firedrake                     |3c589c124b|False     |
|petsc4py            |firedrake                     |3f09f6d   |False     |
|tsfc                |master                        |e6882a1   |False     |
|ufl                 |master                        |bd0376da  |False     |
---------------------------------------------------------------------------
```

**Comment by dham** [comment]
Hi Andreas,

I’m not at a computer right now, however one thing I will note in passing is that you are looking directly at DoF values. Note that the DoF values are the evaluation of the node, not the evaluation of the field at that point. If I recall correctly, the nodes of BDM are the normal scaled by edge length. This might explain some of what you observe.

Regards,

David

PS. What do we actually have to do to dissuade people from using obsolete c string expressions?

Dr David Ham
Department of Mathematics
Imperial College London

On 8 Mar 2018, at 08:19, Andreas Bock <notifications@github.com<mailto:notifications@github.com>> wrote:


Given a CG1 field b, I would like to do a manual projection of dot(b, n) onto a linear Discontinuous Lagrange Trace (DGT1) space (script include below) to detect on which edges this expression vanishes. Since the degrees of freedom for DGT1 correspond to those for BDM1, I have been using the built-in project method for the latter space up until now. I am trying to understand why these two projections are providing very dissimilar values (up to a factor of edge length). In particular, the manual trace projection is not giving me values of dot(b, n) that I recognise. The script below computes both projections for a piece-wise constant b and shows the differences:

MWE:

from firedrake import *
import numpy as np

# mesh & fs
res = 3
mesh = UnitSquareMesh(res, res)
DGT = FunctionSpace(mesh, "DGT", 1)
CG = FunctionSpace(mesh, "CG", 1)

# construct rhs
vl_exp = Expression("x[1]<0.3 || 0.7<x[1] ? 1 : 0")
b = as_vector((Function(CG).interpolate(vl_exp), 1))

# Method 1: manual projection of b.n onto trace function `w1`
u, v = TrialFunction(DGT), TestFunction(DGT)
w1 = Function(DGT)

bbc = DirichletBC(DGT, 0, "on_boundary")
n = FacetNormal(mesh)
solve(u('+')*v('+')*dS == dot(b, n)('+')*v('+')*dS, w1, bcs=bbc)

# Method 2: Compute the BDM1 projection `w2`
BDM = FunctionSpace(mesh, "BDM", 1)
w2 = project(b, BDM)
File("w2.pvd").write(w2)  # visualise to see the strip where `w2` is zero

print("w1 = ", w1.dat.data, "\n")
print("w2 = ", w2.dat.data, "\n")

# Number of zero entries in w{1,2}:
tol = 1e-04
switch1 = Function(DGT).assign(conditional(abs(w1)<tol, 1, 0))

zero_nodes1 = np.unique(np.where(switch1.dat.data_ro_with_halos>tol)[0])
zero_nodes2 = np.unique(np.where(abs(w2.dat.data_ro_with_halos)<tol)[0])

print("zero_nodes1 = ", zero_nodes1, "\n")
print("zero_nodes2 = ", zero_nodes2, "\n")
print("Equal? : ", zero_nodes1 == zero_nodes2)


firedrake-status:

---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|COFFEE              |master                        |5bb1b30   |False     |
|FInAT               |master                        |ef12759   |False     |
|PyOP2               |master                        |8a918cfc  |False     |
|fiat                |master                        |4a201c7   |False     |
|firedrake           |master                        |743c20dc  |False     |
|h5py                |firedrake                     |c1e4a81   |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|petsc               |firedrake                     |3c589c124b|False     |
|petsc4py            |firedrake                     |3f09f6d   |False     |
|tsfc                |master                        |e6882a1   |False     |
|ufl                 |master                        |bd0376da  |False     |
---------------------------------------------------------------------------

**Comment by andreasbock** [comment]
I do not think this explains all of what I see. The scaling cannot explain why the manual projection produces a lot more zeros that what it should when inspecting the expression for the velocity field. However, is there an easy way to get the coordinates `p`of the dof nodes and then using `my_field.evaluate(p)`?

**Comment by wence-** [comment]
Your BDM projection doesn't enforce homogeneous dirichlet conditions, whereas your trace projection does.

**Comment by wence-** [comment]
You either want to write:

```python
solve((u*v)('+')*dS + u*v*ds == (dot(b, n)*v)('+')*dS + dot(b, n)*v*ds, w1)
```
with no boundary conditions,

or write:

```python
bc = DirichletBC(BDM, 0, "on_boundary")
w2 = project(b, BDM, bcs=bc)
```

to enforce the same boundary condition in the BDM projection.

**Comment by andreasbock** [comment]
On second thought, is this due to the placement of the nodes and the edge-length weight? I do not think this is accounted for in the manual projection, and the values of `dot(b, n)` are therefore closer to zero?
