### ISSUE TITLE
add "python3" in demos/Makefile

### ISSUE THREAD

**Issue by bueler** [firedrakeproject/firedrake#1202]
Doing `make demos` outside of venv uses python2 on my machine and generates many errors like
```
SyntaxError: invalid syntax
  File "../pylit/pylit.py", line 1648
    print(line, end=' ')
```
But a fix is easy I think.  Change the last line of Makefile to
```
    for file in */*.py.rst; do python3 ../pylit/pylit.py $$file; done
```
Of course it works fine inside the venv for me.  But it is natural to want to see the raw demos when looking for the first time, even before installation.

**Comment by dham** [comment]
Thanks for spotting this, though the right fix is to fix the shebang line in `pylit.py`, which I have now done.

For the benefit of any potential users who stumble across this issue, it is not necessary to even download Firedrake in order to see the source code for the demos. Every demo has a link to its source code from its documentation page on the Firedrake website. The link is at the bottom of the page.

**Comment by bueler** [comment]
> For the benefit of any potential users who stumble across this issue, it is not necessary
> to even download Firedrake in order to see the source code for the demos. Every demo
> has a link to its source code from its documentation page on the Firedrake website.
> The link is at the bottom of the page.

If you want all the codes runable as a batch (i.e. sans .rst), is running `make demos` in `demos/` the recommended way?

PS Having just failed again to install fenics, the venv route adopted by firedrake is a joy!

**Comment by wence-** [comment]
> If you want all the codes runable as a batch (i.e. sans .rst), is running make demos in demos/ the recommended way?

That's the easiest way, I think.  The presumption is that if you want to run the demos, you'll have a working installation.

For `make demos`, the proposed fixes now in master, so I'll close this issue.

Thanks!
