### ISSUE TITLE
Incorrect results in parallel for Stokes system

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#1212]
If I run the attached firedrake model in serial I get the expected answer, a simple convective cell.
```
$ python testing.py 
    Linear firedrake_0_fieldsplit_1_ solve converged due to CONVERGED_RTOL iterations 16
472.606981717443
40133.808462415465
```
 In parallel I get a different answer with artefacts in the solution near the halo (see velocity_0.pvtu)
```
$ mpirun -np 2 python testing.py 
    Linear firedrake_0_fieldsplit_1_ solve converged due to CONVERGED_RTOL iterations 19
324.90294131427413
324.90294131427413
40197.78413258788
40197.78413258788
```
It's a bit fickle; If I uncomment the 2 lines before the solve to print the jacobian matrix norm, the problem goes away, i.e. parallel and serial produce the same correct velocity solution.

[testing.py](https://gist.githubusercontent.com/stephankramer/acdfd3c0b9c6a20a39b046ac05260d7e/raw/35eae93f710b489a3033f9cd1d6c39ff0ee52c9e/testing.py)

**Comment by wence-** [comment]
This turns out to be a bug that has been extant almost for ever!

We look up a `cell_node_map` in a cache, but for matrices, part of the key is:
```python
        # Ensure bcs is a tuple in a canonical order for the hash key.
        lbcs = tuple(sorted(bcs, key=lambda bc: bc.__hash__()))
```

On different processes, this may sort differently.  If there's a cache miss, we then do:

```python
            nodes = [bc.nodes for bc in lbcs if bc.sub_domain not in ['top', 'bottom']]
```

We do a global_to_local to get the correct boundary nodes.  In this case, what is happening is that you're getting some of the (3, 4) nodes in the halo region mixed in with the (1, 2) nodes, and vice versa.

I'll make a fix.

**Comment by wence-** [comment]
Can you try the referenced branch?
