### ISSUE TITLE
Installation issues with pre-installed petsc and hdf5

### ISSUE THREAD

**Issue by siddhant-wahal** [firedrakeproject/firedrake#1219]
Hello!

I've been trying to install firedrake on a supercomputer ([stampede2](https://portal.tacc.utexas.edu/user-guides/stampede2)). I've run into the following issues:

1. Stampede2 makes almost all libraries available through its module system ([see link](https://portal.tacc.utexas.edu/user-guides/stampede2#using-modules)). This includes PETSC, SLEPc, Python, hdf5, metis, parmetis, MPI to name a few.  Upon running the install script with the ``--no-package-manager``,  ``--honour-pythonpath`` and ``--honour-petsc-dir`` options, I noticed that installing h5py failed with the following error: ``fatal error: can't find source file hdf5.h``. After some digging, I noticed that the install script sets the environment variable ``HDF5_DIR`` equal to ``PETSC_DIR`` (in ``build_and_install_h5py``). Same for ``setup.py`` for the firedrake package (while setting ```firedrake.hdf5interface```). This isn't true on stampede2. Is there a specific reason to do this?

2. Stampede2 has an older version of PETSc (3.7) installed. The install script also failed as it tried to install ``petsc4py``. My guess was that it's pulling the latest version of petsc4py from the index (3.8). Changing the petsc4py version to 3.7.0 led to a successful install of petsc4py. Ideally, the script should check the PETSc version and download the appropriate petsc4py package. 

Would it be possible for you guys to amend the install script? I'm happy to help out, as the rest of my thesis will have to do a lot with firedrake. 

Finally, after a lot of hacking, running ``make alltest`` gave the following error:

``` 
Building extension modules
    Linting firedrake codebase
    Linting firedrake test suite
    Linting firedrake scripts
    Running all regression tests
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
benchmark: 3.1.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home1/03694/siddhant/firedrake/src/firedrake, inifile: setup.cfg
plugins: xdist-1.22.2, forked-0.2, benchmark-3.1.1
collected 0 items / 1 errors

==================================== ERRORS ====================================

______________________________ ERROR collecting  _______________________________
../../lib/python3.6/site-packages/_pytest/config.py:334: in _getconftestmodules
    return self._path2confmods[path]
E   KeyError: local('/home1/03694/siddhant/firedrake/src/firedrake/tests/extrusion')

During handling of the above exception, another exception occurred:
../../lib/python3.6/site-packages/_pytest/config.py:365: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/home1/03694/siddhant/firedrake/src/firedrake/tests/extrusion/conftest.py')

During handling of the above exception, another exception occurred:
../../lib/python3.6/site-packages/_pytest/config.py:371: in _importconftest
    mod = conftestpath.pyimport()
../../lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:955: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:656: in _load_unlocked
    ???
<frozen importlib._bootstrap>:626: in _load_backward_compatible
    ???
../../lib/python3.6/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
tests/extrusion/conftest.py:2: in <module>
    from firedrake import ExtrudedMesh, UnitSquareMesh, UnitIntervalMesh
firedrake/__init__.py:27: in <module>
    firedrake_configuration.setup_cache_dirs()
firedrake_configuration/__init__.py:46: in setup_cache_dirs
    os.environ["PYOP2_CACHE_DIR"] = os.path.join(config["options"]["cache_dir"], "pyop2")
E   TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:
../../lib/python3.6/site-packages/py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
../../lib/python3.6/site-packages/py/_path/common.py:418: in gen
    dirs = self.optsort([p for p in entries
../../lib/python3.6/site-packages/py/_path/common.py:419: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
../../lib/python3.6/site-packages/_pytest/main.py:434: in _recurse
    ihook = self.gethookproxy(path)
../../lib/python3.6/site-packages/_pytest/main.py:338: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
../../lib/python3.6/site-packages/_pytest/config.py:348: in _getconftestmodules
    mod = self._importconftest(conftestpath)
../../lib/python3.6/site-packages/_pytest/config.py:376: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: TypeError("'NoneType' object is not subscriptable",)
E     File "<frozen importlib._bootstrap>", line 971, in _find_and_load
E     File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
E     File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
E     File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
E     File "/home1/03694/siddhant/firedrake/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "/home1/03694/siddhant/firedrake/src/firedrake/tests/extrusion/conftest.py", line 2, in <module>
E       from firedrake import ExtrudedMesh, UnitSquareMesh, UnitIntervalMesh
E     File "/home1/03694/siddhant/firedrake/src/firedrake/firedrake/__init__.py", line 27, in <module>
E       firedrake_configuration.setup_cache_dirs()
E     File "/home1/03694/siddhant/firedrake/src/firedrake/firedrake_configuration/__init__.py", line 46, in setup_cache_dirs
E       os.environ["PYOP2_CACHE_DIR"] = os.path.join(config["options"]["cache_dir"], "pyop2")
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.46 seconds ============================
```

Any help with this issue would be appreciated!
Thanks!

**Comment by dham** [comment]
Hi Siddhant, thanks for your interest in Firedrake.

Firedrake effectively piggy-backs on PETSc's build system to provide it with several compiled dependencies. This is essentially because maintaining build systems robustly is a huge amount of work that we don't want or need to duplicate. So, for example, we get PETSc to build HDF5 for us, but also Eigen and other things. In principle it would be possible to add more options to `firedrake_install` which would enable these dependencies to be pulled from elsewhere, and if you wanted to put in a pull request to that effect then we'd probably accept it. However, I think this is of limited use because of the next issue.

Using the system PETSc installed on a supercomputer is unlikely to work for two reasons:

1. Because Firedrake depends on a whole bunch of PETSc features, and on PETSc to build various things for us, PETSc needs to have been build with a particular minimum set of configure flags. Unless you get lucky, the system PETSc won't have the right set of flags.

2. The PETSc developers change their interface more often than they change their underwear. This means that running with an old version of PETSc will frequently fail. In fact PETSc are also not always totally robust about making sure interface changes are ported to petsc4py. This is the reason that we maintain GitHub forks of PETSc and petsc4py: those versions are tested to ensure they are compatible with each other and with the current Firedrake master. 

Now, it is often a good idea on a supercomputer to use an external PETSc and not rely on Firedrake to build one (not least because building PETSc can be a slow process and you don't want Firedrake to decide to rebuild it on an upgrade without your permission). However in order to do that, the safest option is to build your own PETSc using the configure options from the Firedrake install script (and probably using the Firedrake PETSc fork unless you particularly need a very fresh feature from PETSc master). Having done that, you can use `--honour-petsc-dir` to point to PETSc.

Using `--honour-python-path` is almost always a bad idea. It's much safer to just let Firedrake install everything in its own venv. There is very little utility in using system python packages in almost any circumstances.

Finally, your `make alltest` failure appears to indicate that something went wrong in the installation of the `firedrake_configuration` module. I'm speculating, but that's probably something that just happened in the process of "hacking around". I would build a PETSc as above, run a fresh (non-hacked) install and see if the same error occurs.

Regards,

David

**Comment by wence-** [comment]
I note as well, as regards @dham's point 1.  If you want to use system-installed libraries like hdf5/metis/parmetis with your PETSc, you can indeed do that when building.  You load those modules and then build PETSc telling it about those packages.  The install script documents those packages which we want/need for a useful installation.

**Comment by siddhant-wahal** [comment]
@dham, @wence- Thanks for the detailed replies!

I'll try installing the firedrake fork of PETSc and build firedrake against that. Feel free to close this issue if you like.

**Comment by wence-** [comment]
Great!  Do get in touch if you have any other issues.
