### ISSUE TITLE
Possible License infringiment with PyLit

### ISSUE THREAD

**Issue by edu159** [firedrakeproject/firedrake#1283]
Hi guys, I would probably be interested in using your software which you are licensing under LGPLv3 but I have realised PyLit, which is used inside Firedrake is licensed with GPLv2 or above. This seems to be license infringement according to GNU: 
[https://www.gnu.org/licenses/gpl-faq.html#compat-matrix-footnote-8](url)

According to that table you should be licensing with GPLv3 instead as LGPL is more restrictive.

Pardon me if there is something I am missing and I am wrong.

Cheers

**Comment by wence-** [comment]
Hi,

pylit is not actually required for the running of Firedrake, it is only used to build the demo files.  So for distribution purposes, it is entirely possible to remove pylit and still run everything.  Perhaps @dham can comment further.

**Comment by edu159** [comment]
Hi,  I just want to make sure the licensing is OK as I am bound to some company related OSS policies. I might be wrong in my last message so I wanted to check with you.

Thanks

**Comment by dham** [comment]
Hi Eduardo,

Because pylit is just distributed alongside Firedrake code, there is no licence incompatibility. We would only have that issue if we were distributing binaries linked against pylit, which is technically impossible because pylit is a python script. There is therefore no licensing issue.

Regards,

David

Dr David Ham
Department of Mathematics
Imperial College London

On 11 Sep 2018, at 11:37, Eduardo Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I just want to make sure the licensing is OK as I am bound to some company related OSS policies. I might be wrong in my last message so I wanted to check with you.

Thanks

**Comment by edu159** [comment]
Thanks for the clarification. All clear now.

Regards
