### ISSUE TITLE
Function evaluation on UnitSquareMesh fails at arbitrary points

### ISSUE THREAD

**Issue by alexanderzimmerman** [firedrakeproject/firedrake#1340]
I was verifying a few points of a solution against benchmark values, and surprisingly got an error saying the point (0.5, 0.35) was not within the domain of my unit square mesh.

The following reproduces the issue with firedrake-0.13.0+2351.gb7b1294 .

```python
import firedrake as fe


x = 0.5

for M in range(1, 50):

    print("M = " + str(M))

    mesh = fe.UnitSquareMesh(M, M)

    for y in (0.349, 0.35, 0.351):
    
        print(mesh.coordinates.at((x, y)))
```
    
This issue occurs for about half of the points I originally wanted to check; so now my test code verifies the solution at y coordinates (0., 0.15, 0.34999, 0.5, 0.65, 0.84999, 0.99999) instead of (0., 0.15, 0.35, 0.5, 0.65, 0.85, 1.). This doesn't affect me so much right now, but this is very peculiar.

**Comment by dham** [comment]
This is usually caused by points which are very close to the boundaries of cells. In these cases it is difficult to tell which cell a point is in and Firedrake can sometimes come to the conclusion that the point is in no cells at all. You can adjust for this to some extent by setting the `tolerance` argument to `at`.
