### ISSUE TITLE
Interpolate constant on the R space

### ISSUE THREAD

**Issue by NBoulle** [firedrakeproject/firedrake#1551]
If I try to interpolate a constant on the R space:
```
from firedrake import *
N = 100
mesh = IntervalMesh(N, 0, 1)
R = FunctionSpace(mesh, "R", 0)
a_int = interpolate(Constant(1.0), R)
```
I get `norm(a_int) = 100.0` instead of `1.0`. Using `project` gives me the expected result.

**Comment by wence-** [comment]
This is because interpolation is a point wise thing (it doesn't know about cell volumes) and so it loops over all cells and add the contribution of the expression in that cell to the basis functions on that cell.

It turns out this was a bug in the codegen that happens in this case. I think I have fixed it in OP2/PyOP2#572.

**Comment by wence-** [comment]
Although I have "fixed" this, I think what you are asking for is not mathematically well-defined (it's kind of equivalent to interpolating into a DG0 space). You can do this correctly with `assign`. I am inclined to in addition raise an error if trying to interpolate into a Real space.

**Comment by NBoulle** [comment]
Ok, thank you very much!
