### ISSUE TITLE
Error during PETSc installation 

### ISSUE THREAD

**Issue by jgwilliams17** [firedrakeproject/firedrake#1580]
I received the following error trying to run firedrake-update:

File "../bin/firedrake-update", line 1251 in <module>
os.symlink(src, dest)
FileExistsError: [Errno 17] File exists: '/firedrake/src/petsc/default/bin/mpicc' -> 'firedrake/bin/mpicc'

I then tried removing firedrake and re-installing. I now get a new error: the attached firedrake-install.log when installing PETSc, which points to the PETSc configure.log file where there is the message:

Fatal Error: mpif.h: No such file or directory

I am struggling to figure out what has happened here - any pointers would be very much appreciated!
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4061918/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/4061920/configure.log)

**Comment by dham** [comment]
This is a problem in pragmatic, which is an external dependency of Firedrake. Essentially what is happening is that pragmatic is using header files from open-mpi, which are in /usr/local/include instead of the correct ones from the MPICH directory in your firedrake install. As workarounds, you might be able to try `brew unlink open-mpi` or, if you don't have anything else installed that needs mpi `brew uninstall open-mpi`.

**Comment by wence-** [comment]
Plausibly relevant: meshadaptation/pragmatic#122

**Comment by wence-** [comment]
Possible fix on our side is to remove `--download-pragmatic` from the default set of petsc packages.

**Comment by dham** [comment]
Yes, I think that's probably the way to go. There are a bunch of lines in the pragmatic cmake file which could be doing the spurious insertion, and I lack both the expertise and the time to debug that.

**Comment by jgwilliams17** [comment]
Thank you both so much for getting back to me so quickly. I have uninstalled open-mpi as suggested as a workaround, and the install looks to have made it past the problematic stage.
