### ISSUE TITLE
Stability/implementation issue concerning Euler's fluid equations

### ISSUE THREAD

**Issue by dwb26** [firedrakeproject/firedrake#1599]
Apologies in advance if this is not the correct procedure to go about resolving this issue, but it's somewhat of a last ditch and I'm very reluctant to give up on Firedrake.

The weak variational problem I have is, as per SciComp Stack:

https://scicomp.stackexchange.com/questions/34326/defining-appropriate-test-function-spaces-for-the-finite-element-solution-of-eul

For what it's worth, some bare bones of my attempt is the following (please change the filetype to .py)

[detect.txt](https://github.com/firedrakeproject/firedrake/files/4150334/detect.txt)

The issue is that the results aren't physically intuitive using CG FunctionSpace (and therefore incorrect), and in worst cases of DG FunctionSpace, diverge. I feel this may be due to the choice of function space, the choice of time discretisation (I've used Backward implicit Euler), or an incorrect choice of the pre-conditioner parameters. For reasons of similarity (1st order coupled PDE), I've used Colin Cotter's Camassa-Holm example as a guide:

https://firedrakeproject.org/demos/camassaholm.py.html

but perhaps it's not applicable to this problem (one difference being that Euler's equations are non-linear). 

Any guidance, ideas or advice at this point would be hugely welcome. Thanks in advance, and if I can provide any further information then please let me know.

**Comment by dham** [comment]
The code you have posted uses CG1 elements for both velocity and pressure. This is a known unstable element pair. Just switching to DG elements is not a valid thing to do, because you would be implicitly dropping a whole load of element facet integrals, which is a mathematically invalid thing to do.

Numerical methods for fluid equations are quite non-trivial, just writing up the simplest discretisation won't work (and also won't work in finite differences or finite volumes). The Gusto atmospheric dynamical core has an incompressible Euler solver written in Firedrake, (https://firedrakeproject.org/gusto) and there is a discussion of the discretisation involved, including relevant function spaces, in: https://arxiv.org/pdf/1910.01857.pdf

Note that this is not actually an issue with Firedrake. If you feed unstable or incorrect numerics into Firedrake, then it will correctly give you garbage back. Unfortunately, we can't do your numerical analysis for you!
