### ISSUE TITLE
Time-dependent DirichetBC

### ISSUE THREAD

**Issue by rckirby** [firedrakeproject/firedrake#1614]
Firedrake does not seem to be picking up changes to an Expr-based value being set in a Dirichlet boundary condition when a Const inside the Expr (e.g. time) is changed.  A small failing example is attached.

[be.py.txt](https://github.com/firedrakeproject/firedrake/files/4245268/be.py.txt)

**Comment by wence-** [comment]
Thanks, this is an issue because the bc object doesn't reinterpolate the expression when values inside it changed. There are three fixes, in increasing order of goodness:

### 1. refactor your code

```python
bcexpr = ...
bcvals = Function(V)
bcvals.interpolate(bcexpr)
bc = DirichletBC(V, bcvals, ...)
while ...:
    ...
    bcvals.interpolate(bcexpr)
```

You can also use an `Interpolator` to speed this up a little.

### 2. Always reinterpolate inside `bc.apply`

That is, change `DirichletBC` to do
```
...
bc_func.interpolate(bc_expr)
bc.apply(...)
```

### 3. Reinterpolate inside `bc.apply` but only when state has changed

This requires us (and it's necessary for some other things) to reinstate object state tracking in PyOP2 and then hook that up in all of these "magic" functions.

**Comment by rckirby** [comment]
So the "right" solution I think is #3 but probably out of reach for now.  I'll close this and use #1 for now.
