### ISSUE TITLE
improve checkpointing

### ISSUE THREAD

**Issue by danshapero** [firedrakeproject/firedrake#1649]
The current interface for checkpointing makes several restrictive assumptions and removing these assumptions would make life easier for end users. Right now, a checkpoint can only be read on the same number of processes as it was created with. A typical use case that's currently impossible is that you run an expensive simulation on several processes, write the output to a checkpoint, and then use a separate script to make a visualization of the result. That plotting script now has to run on the same number of MPI processes as the simulation itself.

Right now, writing a `Function` to a `DumbCheckpoint` only writes the vector of coefficients on each process. A better checkpoint would require also saving, at minimum:

* the mesh
* function space
* PETSc section describing the data layout

For extruded meshes there's some extra data about the extrusion. By saving this data, the checkpoint object now knows how to interpret the coefficient data.

A good first step will be figuring out how to write a PETSc DMPlex to a file and then read it back on a different number of processes. [This example](https://www.mcs.anl.gov/petsc/petsc-current/src/dm/impls/plex/tutorials/ex5.c.html) from the PETSc documentation does a write/read roundtrip using both HDF5 and Exodus formats.

Supersedes #1080 .

**Comment by alexanderzimmerman** [comment]
@danshapero , is the scope of this issue entirely related to distributed memory parallel processing, or do you have other improvements in mind? All of the limitations I read in limitations mentioned in [the docs](https://www.firedrakeproject.org/checkpointing.html) are indeed related to changing the number of processes.

**Comment by danshapero** [comment]
@alexanderzimmerman The big problem to address is reading/writing on different numbers of parallel processes. I suppose it isn't several restrictive assumptions that the current API makes, really just one big one. Were there other improvements you'd like to see?

If you're storing the mesh and function space in the checkpoint file as well, it may be possible to make other code shorter. For example, right now you have to load in the mesh you used in the first place, create a function space, create a function, and then load its values. In principle you could cut this down to a single step. But fixing this issue won't be trivial and I think it's best to keep each pull request as small as possible.

**Comment by alexanderzimmerman** [comment]
Thanks for clarifying. I am just now implementing checkpointing/restarting in my user code and I wanted to make sure I understand the roadmap of anyone changing that functionality in Firedrake.


Regarding other improvements on my mind, there's only one right now:

Has anyone looked into supporting `pickle`? A few years ago I would have assumed that `h5py` is a better choice than `pickle`; but I'm having trouble finding evidence of that today. Maybe today the right thing to do is to support `pickle`.

For me the biggest limitation of `pickle` has always been that it's not necessarily portable between different versions of Python. But I also don't imagine Firedrake has any intention to make its checkpointing/restarting portable across versions of Firedrake, so `pickle` seems like a natural fit.

Right now I can't pickle one of my Firedrake simulations because I can't pickle a `petsc4py.PETSc.DMPlex` object. I would have to look further to see if there are other troublesome objects. I think that a `__reduce__` method must be implemented for each class so that their objects can be pickled. 
Pickling a `petsc4py.PETSc.DMPlex` object could address the "good first step" you mentioned above.

**Comment by dham** [comment]
Pickle isn't the right answer to this problem. This is for several reasons:

1. It's Python-specific but, as you've noticed, significant chunks of what we need to save are actually wrapped PETSc objects.
2. The Python versions issue is actually a big deal. Some users want to dump Firedrake data for later analysis, rather than just to restart a simulation.
3. Pickle really doesn't support the restart on other processes operation.
4. I doubt it's anywhere near the performance of HDF5 and competitors. It's an object serialisation solution rather than a mechanism for dumping bulk data to disk.

**Comment by alexanderzimmerman** [comment]
I would have been surprised if `pickle` was the right solution; but I am somewhat naive and I am glad to have reasons against it written down nearby as long as the checkpointing code is being re-worked. Thanks @dham !

Also I just went through the exercise of starting to write a Pickler for one of my simulation classes using `firedrake`, mostly to discover which objects couldn't already be pickled. The first unpicklable object which comes up is the `petsc4py.PETSc.DMPlex`; but there are many more spanning at least  `mpi4py` in addition to `firedrake` and `petsc4py`. It would be quite a large ecosystem change, and I am sure none of this has been done because of @dham 's points above.

Some side notes as long as we are figuring out how to write meshes to disk:
* I also started a simpler exercise of writing a Pickler for a `firedrake.Mesh`, and I was surprised to find that `firedrake.Mesh` is a function rather than a class.
* @dham and I had some brief discussions about more fully embracing DMPlex in Firedrake, especially how it handles mesh topology. Is that still being considered? If so, then maybe that should be changed before writing the code for storing meshes.

**Comment by danshapero** [comment]
Just a brief update -- I started working on this but quickly ran into a roadblock. When I tried to save a PETSc DMPlex object to HDF5, I wasn't able to save the mesh under a group, only under `/`. Having some kind of namespace mechanism will be necessary if we want to save more than one mesh to the same checkpoint file. I asked the PETSc mailing list about this and apparently it's because visualization software expects only one mesh and possibly several fields in one HDF file. But they're overhauling how viewers work right now anyway and the developers seemed to think this was a reasonable feature to add. So improving checkpointing in Firedrake will have to wait for now on some changes to PETSc.

**Comment by tkarna** [comment]
This sounds great! To the wishlist: In order to save disk space, it would be great if (optionally?) the mesh would not be included in every checkpoint file. That is, there would be a single mesh file (or function space file) and many checkpoint files which only contain the DOF coefficients.
