### ISSUE TITLE
slate kernels on extruded meshes encode mesh layers

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#1715]
This is bad. Moreover, the in memory cache key doesn't include it, so we get the wrong answer.

**Comment by sv2518** [comment]
Ok, I have just had a look. The core of the problem is here https://github.com/firedrakeproject/firedrake/blob/ddba1d21ca37f2c9570998a586e6f42a644b83da/firedrake/slate/slac/compiler.py#L487. We want avoid that, so we do not have to reproduce the Slate code as soon as the users decides to change the amount of layers, is that right?
To fix this we need to think about what we are going to do here https://github.com/firedrakeproject/firedrake/blob/ddba1d21ca37f2c9570998a586e6f42a644b83da/firedrake/slate/slac/compiler.py#L494. Is the idea to pass another argument to the Slate kernel from PyOP2, which contains what is currently in the `num_layers`?

**Comment by wence-** [comment]
> Is the idea to pass another argument to the Slate kernel from PyOP2, which contains what is currently in the num_layers?

Yes, I think so. We currently have `pass_layer_arg` as an option on par_loops (really we should migrate that to kernels and call it `pass_current_layer`), if we also add `pass_num_layers` then we can inspect that in codegen and generate the extra argument. I propose we don't do it in current slate compiler, but in the new one.

**Comment by sv2518** [comment]
Oh ok, I have had a look at the current Slate compiler and have a propose for a fix for that, it's here: https://github.com/firedrakeproject/firedrake/compare/fix-variable-layer-count.
I pass the layer number as a Global arg in assemble. The Slate kernel has an additional parameter carrying the layer number. It passes at least all tests in tests/slate/test_facet_tensors_extr.py.
The kwarg `pass_layer_arg` results in layer passed in as int, I don't think we can inspect that on slate level. I think, we need the number of the layers as the separate argument to the slate kernel.

**Comment by wence-** [comment]
Thanks!
