### ISSUE TITLE
Ubuntu 16.04 installation failure

### ISSUE THREAD

**Issue by swarder** [firedrakeproject/firedrake#1781]
Hi,

I'm running into problems installing on Ubuntu 16.04 - log attached

I see that Ubuntu 18.04 is the officially supported version, but I'd prefer to avoid upgrading if possible...

Thanks in advance for your help,
Simon

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4931158/firedrake-install.log)

**Comment by dham** [comment]
You appear to be missing the Python headers. Because you need to use a Python other than the system default python (system python3 on 16.04 is 3.5 which is too old), the installer does not install the python headers for you. If you installed Python 3.6 using an ubuntu package called python3.6 then you probably need libpython3.6-dev too.

**Comment by swarder** [comment]
Thanks David, I've got further now but hitting another issue. Log attached again.

Thanks,
Simon

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4936643/firedrake-install.log)

**Comment by dham** [comment]
Cmake is barfing when building libsupermesh. I'm really not very good at understanding Cmake but maybe it indicates your cmake is too old? This is @jrmaddison's code so you might need to ask him.

**Comment by wence-** [comment]
I think you need cmake >= 3.7

**Comment by swarder** [comment]
Thanks very much David and Lawrence, it's installed now after upgrading to the latest cmake
