### ISSUE TITLE
Errors in Upgrade firedrake

### ISSUE THREAD

**Issue by xiaodizhang29** [firedrakeproject/firedrake#1869]
I am a student in Software engineering running Firedrake for a research project. I am upgrading the firedrake. But it does not work. Could you tell me how to handle this? 

![image](https://user-images.githubusercontent.com/43510798/96084090-0c3a8100-0ef1-11eb-92a4-9db6765b8dd5.png)

[update.log](https://github.com/firedrakeproject/firedrake/files/5382794/update.log)

And when I am employing the Raviart Thomas finite element, threre is a warning,

![image](https://user-images.githubusercontent.com/43510798/96084674-0d1fe280-0ef2-11eb-89e9-f6525fb96d8d.png)

Could you help me to remove this warning?

**Comment by danshapero** [comment]
The error message says "could not resolve host: github.com". It looks like your internet access may have cut out while you were upgrading.

The warning you're getting from Raviart-Thomas elements is a separate problem; it's fine now but it's easiest for us in future if you make separate issues. Something like this code should work:

```python
mesh = UnitSquareMesh(16, 16)
element = FiniteElement(family='RT', cell='triangle', degree=1, variant='integral')
V = FunctionSpace(mesh, element)
```

Here instead of creating the function space all at once, we're separately creating an element object first and then creating a function space. If you're working on, say, a quad mesh, you'll pass a different cell type instead of `'triangle'`. Can you try that and see if it works? If it does we can close this issue.

**Comment by xiaodizhang29** [comment]
Thank you for your kindness, I'll appreciate it.

**Comment by xiaodizhang29** [comment]
It can work now, thank you for your kindness, I'll appreciate it.
