### ISSUE TITLE
Unable to load the mesh I've created in gmsh

### ISSUE THREAD

**Issue by jgwilliams17** [firedrakeproject/firedrake#1919]
[files.zip](https://github.com/firedrakeproject/firedrake/files/5556893/files.zip)
I receive the error "Could not determine Plex facet for GMesh element 1 (Plex cell 0)" when I try to import the gmsh file cylinder.msh I have created.

I have attached a minimal working example (test.py) as well as the mesh file in both .msh and .geo formats. 

Any help would be very much appreciated.

**Comment by ksagiyam** [comment]
I found that `gmsh -2 -format msh2 cylinder.geo` (from a relevant Slack conversation) at least generates a loadable `.msh` file, though it tosses many `syntax error`s.

**Comment by jgwilliams17** [comment]
Thank you so much @ksagiyam - sorry I'd missed seeing this until now. I can also load the mesh file when I run the command you stated. However, if I want a 3D mesh, do I not need to run "gmsh -3 -format msh2 cylinder.geo"? If I do this then I am unable to load the mesh.

**Comment by danshapero** [comment]
@jgwilliams17 I just tried to generate a .msh file from your .geo file using `gmsh -3 -format msh2 cylinder.geo`. I get the following error when I try to load it:

```
[0] DMPlexCreateFromFile() line 3642 in /home/daniel/.pyenv/versions/firedrake-python3.9/src/petsc/src/dm/impls/plex/plexcreate.c
[0] DMPlexCreateGmshFromFile() line 1409 in /home/daniel/.pyenv/versions/firedrake-python3.9/src/petsc/src/dm/impls/plex/plexgmsh.c
[0] DMPlexCreateGmsh() line 1675 in /home/daniel/.pyenv/versions/firedrake-python3.9/src/petsc/src/dm/impls/plex/plexgmsh.c
[0] No support for this operation for this object type
[0] Could not determine Plex facet for Gmsh element 1 (Plex cell 1049)
```

I had a look at the PETSc source code; it looks like the error comes from inability to reconstruct the full mesh topology. So I think that this is either a shortcoming of PETSc's gmsh reader or there's something wrong with the input geometry. (I still don't understand how to write .geo files correctly if that makes you feel any better.) If all you need to do is get a tetrahedral mesh of a cylinder, you could try one of the functions in [pygmsh](https://pypi.org/project/pygmsh/) instead of creating the input file yourself.

Feel free to drop by the [slack channel](https://firedrakeproject.org/contact.html) if you want a hand with this, but since this doesn't appear to be a Firedrake issue as such I'm closing it.
