### ISSUE TITLE
InterpolateBlock does not store interpolators

### ISSUE THREAD

**Issue by ReubenHill** [firedrakeproject/firedrake#1981]
The current `InterpolateBlock` creates a new `Interpolator` every time something needs interpolating. These should be stashed somehow. 

 @nbouziani has, I believe, dealt with similar issues (possibly in #1674?) - he may be able to provide some insight. We could perhaps stash the new interpolators on the `interpolator` originally used to create the block?

**Comment by nbouziani** [comment]
I have not dealt with similar issues in #1674 since the interpolate is part of the external operator evaluation process (happens inside the external operator), that is there is no additional `InterpolateBlock` induced.

Just to be sure I understand correctly: You want to stash `Interpolator(expr, space)` right ? Is it not just when you interpolate via `Interpolator(expr, space).interpolate(...)` that there is a computational cost ? If yes, then I don't understand the problem with defining a new `Interpolator` every time something needs interpolating.

**Comment by ReubenHill** [comment]
Woops - duplicate issue. Mind recommenting on #1962?
