### ISSUE TITLE
Compiling failure in CentOS 6

### ISSUE THREAD

**Issue by klaatujk** [firedrakeproject/firedrake#2056]
In addition to M1 Macbook pro, I am trying to install firedrake in CentOS 6.
Compiling is failed with the message below.
I did do my best what I can do, but I have no idea after failing.
I will appreciate for any comment and suggest.

Depending on your platform, PETSc may take an hour or more to build!
Installing pip dependencies for petsc4py
No dependencies found. Skipping.
Installing pip dependencies for COFFEE
Traceback (most recent call last):
  File "firedrake-install", line 1589, in <module>
    pip_requirements(p, compiler_env)
  File "firedrake-install", line 812, in pip_requirements
    run_pip_install(["--no-deps", "-r", "%s/requirements.txt" % package])
  File "firedrake-install", line 781, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 520, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/home/klaatu02/.linuxbrew/opt/python@3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/klaatu02/.linuxbrew/opt/python@3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/klaatu02/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy,scipy', '-vvv', '--no-deps', '-r', 'COFFEE/requirements.txt']' returned non-zero exit status 1.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6422380/firedrake-install.log)

**Comment by JDBetteridge** [comment]
Relevant lines are:
```
gcc -pthread -shared -L/home/klaatu02/.linuxbrew/lib /home/klaatu02/.linuxbrew/opt/python@3.7/lib /home/klaatu02/.linuxbrew/opt/python@3.7/include build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/numpy/core/src/multiarray/_multiarray_tests.o build/temp.linux-x86_64-3.7/numpy/core/src/common/mem_overlap.o -L/home/klaatu02/.linuxbrew/lib -L/home/klaatu02/.linuxbrew/opt/openssl@1.1/lib -L/home/klaatu02/.linuxbrew/opt/sqlite/lib -L/home/klaatu02/.linuxbrew/opt/python@3.7/lib -Lbuild/temp.linux-x86_64-3.7 -lnpymath -lpython3.7m -o build/lib.linux-x86_64-3.7/numpy/core/_multiarray_tests.cpython-37m-x86_64-linux-gnu.so
  /home/klaatu02/.linuxbrew/bin/ld: error: /home/klaatu02/.linuxbrew/opt/python@3.7/lib: read: Is a directory
  collect2: error: ld returned 1 exit status
```

I'm not sure what linuxbrew is, but something is adding this to the compiler options and needs to be fixed:
I notice that these environment variables are set:
```bash
LDFLAGS=/home/klaatu02/.linuxbrew/opt/python@3.7/lib
CPPFLAGS=/home/klaatu02/.linuxbrew/opt/python@3.7/include
```
**If** you set them yourself they should read:
```bash
LDFLAGS=-L/home/klaatu02/.linuxbrew/opt/python@3.7/lib
CPPFLAGS=-I/home/klaatu02/.linuxbrew/opt/python@3.7/include
```
**else** you need to find what is setting these variables (perhaps linuxbrew) on your system and correct that first.

**Comment by wence-** [comment]
> I'm not sure what linuxbrew is

Homebrew for linux-based systems.

**Comment by klaatujk** [comment]
Thank you  @JDBetteridge .
I have some progress and errors around PyOP2.
I tried to solve it but I was not able to find solutions.
Please direct me how I can deal with it.


Failed to clone COFFEE using ssh, falling back to https.
Successfully cloned repository COFFEE.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning loopy

Failed to clone loopy using ssh, falling back to https.
Successfully cloned repository loopy.
Checking out branch firedrake
Successfully checked out branch firedrake
Updating submodules.
Successfully updated submodules.
Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Installing pip dependencies for petsc4py
No dependencies found. Skipping.
Installing pip dependencies for COFFEE
Installing pip dependencies for loopy
Installing pip dependencies for ufl
No dependencies found. Skipping.
Installing pip dependencies for fiat
No dependencies found. Skipping.
Installing pip dependencies for FInAT
Installing pip dependencies for tsfc
Installing pip dependencies for PyOP2
Traceback (most recent call last):
  File "firedrake-install", line 1589, in <module>
    pip_requirements(p, compiler_env)
  File "firedrake-install", line 807, in pip_requirements
    run_pip_install_wrap(reqs, parallel_compiler_env)
  File "firedrake-install", line 798, in run_pip_install_wrap
    run_pip_install([req])
  File "firedrake-install", line 781, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 520, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/home/klaatu02/.linuxbrew/opt/python@3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/klaatu02/.linuxbrew/opt/python@3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/klaatu02/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy,scipy', '-vvv', 'mpi4py>=1.3.1']' returned non-zero exit status 1.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6425099/firedrake-install.log)

**Comment by JDBetteridge** [comment]
Okay, we're making progress. The error is here:
```
error: Cannot link MPI programs. Check your configuration!!!
```
This occurs after calling `ld` a bunch of times looking for your MPI shared library. The `ld` that is being called is the linuxbrew one ` /home/klaatu02/.linuxbrew/bin/ld`, you should be able to verify this by running:
```
which ld
```
First thing to check is whether this is the `ld` you want to use, or do you want to use the system linker (normally `/usr/bin/ld`), make sure your `$PATH` environment variable is setup so that `which ld` returns the linker you want to use. (Or change linuxbrew settings to prevent it being used).

Then we need to ensure the linker can find the MPI libraries. When building PETSc the `dl` library was successfully linked against, but when building mpi4py the install fails. You can check at the command line by running:
```
ld -ldl
```
If you see `ld: cannot find -ldl` then there is an issue and you need to make sure that the relevant libraries are appended to the `$LD_LIBRARY_PATH`
If you see `ld: warning: cannot find entry symbol _start; not setting start address` this means it can find the `dl` library and `ld` is working correctly. `dl` is just one library, but once you have fixed the linker it should be able to find all the relevant libraries.

To save having to keep reinstalling firedrake to test this I suggest you try installing mpi4py into your current venv `/home/klaatu02/firedrake` or make a new venv to test the `mpi4py` install. You should use the command:
```
python -m pip install --no-build-isolation --no-binary mpi4py,randomgen,islpy,numpy,scipy -vvv mpi4py>=1.3.1
```
to install, as this is what the install script will use. (If you're using a fresh venv to test, you will need to pip install cython and wheel before this command will work)

**Comment by klaatujk** [comment]
I have given up and turned to install Ubuntu 20.04 on a server.
Then, I could save my life.
Firedrake and Thetis were easily installed.
You cannot believe how I was surprised. 

Thanks, @JDBetteridge and @wence for your comments.

**Comment by wence-** [comment]
Ah, thanks. We will close this issue.
