### ISSUE TITLE
Demo .py files not available/link broken

### ISSUE THREAD

**Issue by bensworth** [firedrakeproject/firedrake#2110]
All of the demo files have a link to access a raw python file to run, e.g.,` and can be found as a script in poisson_mixed.py`, but none of the links work, e.g., https://github.com/firedrakeproject/firedrake/blob/master/demos/poisson/poisson_mixed.py

**Comment by wence-** [comment]
Ah, that's because in the repository, the demo is maintained as an `rst` file. These links work correctly on the generated website (e.g. https://www.firedrakeproject.org/demos/helmholtz.py.html links to https://www.firedrakeproject.org/demos/helmholtz.py). If you want to make the demos locally in your checked out repository, do `make demos` in the `demos` subdirectory of the firedrake checkout.
