### ISSUE TITLE
OMP_NUM_THREADS warning

### ISSUE THREAD

**Issue by adiegel** [firedrakeproject/firedrake#2145]
Hi All,

I just updated my Firedrake install and now I am getting the warning message: 

firedrake:WARNING OMP_NUM_THREADS is not set or is set to a value greater than 1, we suggest setting OMP_NUM_THREADS=1 to improve performance

How do I set the number of threads? 

Thanks!

**Comment by rckirby** [comment]
It's an environment variable and can be set on the command line or in your
profile/shell startup.

**Comment by adiegel** [comment]
Thanks, @rckirby. After your quick response, I found this https://github.com/numpy/numpy/issues/11826 which gave me the exact command I needed.

**Comment by hw454** [comment]
Hi I'm having this issue also. I can rectify it using: 'export OMP_NUMTHREADS=1' on command line but I'm having to do this everytime I activate the environment.
Is there a way to update the virtual environment so that this is set automatically every time I activate?

**Comment by connorjward** [comment]
You could in theory modify the `firedrake/bin/activate` file to include the `export OMP_NUM_THREADS=1` line, but the more standard way to do this is to add the line to your `~/.bashrc` file (assuming you're using Bash). That way this variable gets set every time you launch a terminal and persists across Firedrake installations.

Also, it would be better to open a new issue referencing this one rather than posting at the bottom.
