### ISSUE TITLE
Errors when running make alltest

### ISSUE THREAD

**Issue by dnlbnd40** [firedrakeproject/firedrake#2214]
I am trying to get Firedrake to function on my Windows 10 machine. When I run make alltest, I get an ImportError message and ModuleNotFoundError message, which can be viewed at this link:
https://user-images.githubusercontent.com/90576935/133002870-3a1768a0-569a-48e2-a687-3af749c507de.png

I am running this on Ubuntu 20.04.3

**Comment by dham** [comment]
Please post `firedrake-install.log`. This file will have been created in the folder where you ran `firedrake-install`.

**Comment by dnlbnd40** [comment]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/7164860/firedrake-install.log)

Here is the file.

**Comment by danshapero** [comment]
Sorry for the slow reply -- when the Firedrake install script runs, it first creates a Python [virtual environment](https://docs.python.org/3/tutorial/venv.html). The end of that log says that the install failed because it couldn't create a virtual environment in a folder that already exists. So it seems like you might have tried to install Firedrake, had the install fail for a reason we can't see, and then tried again, only to be unable to overwrite the remains of the old attempt. The remedy for this is to delete the folder where you installed it and try again. If that also fails, please feel free to reply to this issue with the log and we can try to diagnose.

Note that if you're on Windows you'll almost certainly need to have WSL2; as per #2039 the install will probably fail on WSL1.

**Comment by dnlbnd40** [comment]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/7231875/firedrake-install.log)
Here is the updated install log. I deleted all of the folders that firedrake created, and I ran the install process again. However, I am still getting the error messages when running make alltest:

**Comment by dnlbnd40** [comment]
I also ensured that I was running Ubuntu on WSL2

**Comment by danshapero** [comment]
Thanks, this is exactly what we needed! So it looks like the install failed when building libsupermesh because it tried to provide special optimization flags for the Intel Tiger Lake architecture (line 26486 of the log). I think we can find a way to disable some of the optimization flags as a temporary workaround. Stand by while I figure out how to do that...

**Comment by dnlbnd40** [comment]
Good afternoon. I am sorry for the extremely late response. I got a more recent compiler (gcc-10.3 and g++-10.3), but I am still having problems running make alltest and pytest. I have attached my latest firedrake install log. Thank you so much for all of your help so far. I hope we can find a solution soon!
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/7356029/firedrake-install.log)

**Comment by DWolfr** [comment]
> Thanks, this is exactly what we needed! So it looks like the install failed when building libsupermesh because it tried to provide special optimization flags for the Intel Tiger Lake architecture (line 26486 of the log). It also looks like you're using gcc-9.3, but from looking at the release notes, the `-march=tigerlake` option was only added in gcc-9.4.
> 
> Your first option here is to get a more recent compiler version and switch to it using the `update-alternatives` command. The default on Ubuntu 20.04 (which is what you get when using WSL) is to use gcc-9.3. You can install gcc-10, g++-10, and gfortran-10 using apt-get, but your system will still use the old version by default. To switch to the newer version, you can follow the instructions on [this page](https://www.fosslinux.com/39386/how-to-install-multiple-versions-of-gcc-and-g-on-ubuntu-20-04.htm).
> 
> If you don't want to switch compiler versions, I think we can find a way to disable some of the optimization flags as a workaround, but it'll take me a bit to figure out how to do that.

Thanks @danshapero for the solution to the problem. It solves the installation problem for Ubuntu 20.04 using a intel i5-11XXXX processor.

Unfortunately using
```python
from firedrake import *
```
results in the warning
```
firedrake:WARNING OMP_NUM_THREADS is not set or is set to a value greater than 1, we suggest setting OMP_NUM_THREADS=1 to improve performance
```
Is this a known problem, or did we miss something in the installation?

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/7505476/firedrake-install.log)

**Comment by dham** [comment]
The warning means what it says. Firedrake doesn't use OpenMP, but some of the libraries Firedrake uses link to OpenMP. Unfortunately, OpenMP has  really dumb default to spawning a number of OpenMP threads equal to the number of cores on your machine. This can actually cause the code to run more slowly as some libraries spuriously attempt to us OpenMP for the very small problems they control. 

The number of threads that OpenMP uses is controlled by the environment variable OMP_NUM_THREADS. You control that, we don't. The only thing we can therefore do is detect that you haven't set it and warn you to do so.

**Comment by DWolfr** [comment]
Thank you for the fast reply and the information.

**Comment by danshapero** [comment]
It sounds like the problem has been fixed so I'm going to close this issue, but feel free to reopen if need be.
