### ISSUE TITLE
Unclear BLAS warning on Firedrake import

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#2217]
As part of our checks for a multithreaded BLAS we sometimes spew the warning `firedrake:WARNING Could not find BLAS library!`. This has worried a number of users who think that there is a serious problem with their install. Could we make this message less scary?

**Comment by danshapero** [comment]
So the state of affairs before was that we would search in system paths for OpenBLAS and warn if it couldn't be found. This would throw out warnings even more frequently because it missed a bunch of cases: you got PETSc to install OpenBLAS; you're using MKL instead; you're using boring old Netlib BLAS; and so forth. I tried to improve this in #2205 and #2215 by eliminating some of the circumstances where we either can't detect a BLAS library or can't select the number of threads. But both of those PRs are assuming we still want to throw a warning in some circumstances, and I think it would be better to log that information at a lower level (info or debug). Beginning users don't care about performance, while advanced users should read the documentation on perf tuning if they do care.
