### ISSUE TITLE
honour-petsc4py

### ISSUE THREAD

**Issue by qbisi** [firedrakeproject/firedrake#2314]
I am using a self built petsc package installed in /opt/petsc/intel-mkl-real with chmod 755 owned by root. Also built with petsc4py support.
Then i configure firedrake with (user privilage):
python3.9 firedrake-install --disable-ssh --no-package-manager --mpicc mpiicc --mpicxx mpiicpc --mpif90 mpiifort --mpiexec mpiexec --honour-pythonpath --honour-petsc-dir.
Still the firedrake-install script tries to rebuild petsc4py thought it is prebuilt in PYTHONPATH.
If firedrake insists build petsc4py from source ,it requires write privileges' to /opt/petsc/src/bindings/petsc4py ,which is not allow for a shared package. 
I suggest detect petsc4py in pythonpath first ,if not exsits ,copy and build the petsc4py source file (or download from web) in the cache directory

**Comment by wence-** [comment]
Thanks, this is, I think, because since pip version 21.3, `pip install local_directory` does an in-tree build (see the discussion in pypa/pip#7555, and documentation https://pip.pypa.io/en/latest/cli/pip_install/#local-project-installs). The backwards compatibility option is going away in pip 22.1, so we can use the stop-gap proposed there but not for long.

It seems that one way to fix this would be to migrate petsc4py away from a setuptools-based install procedure to something else, but I have lost track of current state of the art in python packaging.

Probably the right workaround is to do as you suggest and copy before installing: @JDBetteridge can you give this a go?

**Comment by JDBetteridge** [comment]
Hmm, I see the dilemma. I'll look into a possible fix for an uneditable system PETSc/petsc4py build of Firedrake

**Comment by JDBetteridge** [comment]
Please try the install script in this PR https://github.com/firedrakeproject/firedrake/pull/2326

Can be obtained with `curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/cb3eb69e23ebb4a3fc97f43b057661a52fa0c633/scripts/firedrake-install`

**Comment by JDBetteridge** [comment]
Fixed in #2326
