### ISSUE TITLE
Some questions about Slate

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2508]
I use LDG method + Backward Euler to solve the heat equation (`PeriodicRectangleMesh`),  then get the matrix
$\begin{pmatrix}A_{00} & A_{01} \\\\ A_{10} & A_{11} \end{pmatrix} \begin{pmatrix} U \\\\ P \end{pmatrix} =  \begin{pmatrix} F \\\\0 \end{pmatrix}$

This can be transformed into solving the following system of linear equations
$\left(A_{00} - A_{01} ( A_{11}^{-1} A_{10})\right) U = F$

I use Slate to achieve as follows:
```python 
....
DG = FunctionSpace(mesh, "DG", Pk)
DG_Vec = VectorFunctionSpace(mesh, "DG", Pk)
MixedSpace = DG * DG_Vec

u_trial, q_trial = TrialFunctions(MixedSpace )
v, w = TestFunctions(MixedSpace )

u_flux = avg(u_trial)
q_flux = avg(q_trial)
A00 = u_trial*v*dx 
A01 = - dtc*(-dot(q_trial,grad(v))*dx + dot(q_flux,jump( v,n))*dS )
A11 = dot(q_trial,w)*dx
A10 = - (-u_trial*div(w)*dx + u_flux*jump(w,n)*dS)
LHS = A00 +A01 + A10 + A11 

RHS = u*v*dx

# Slate 
A = Tensor(LHS).blocks   
a_new = A[0,0] - A[0,1] * A[1,1].inv * A[1,0]
RHS_Tensor = Tensor(RHS).blocks 
b_new = RHS_Tensor[0]

u_solution = Function(DG)

while (t < FinalTime ):
    a_m = assemble(a_new)
    b_m = assemble(b_new)

    solve(a_m, u_solution, b_m)
    u.assign(u_solution)
```
But the result is wrong now.

So I check the block A00, A01, A10 and A11.  
A00 and A11 are the mass matrix(No information exchange between different cells), so  `A[0,0]`  and `A[1,1]`   are equal to `A[0:n, 0:n]` and `A[n+1:-1, n+1:-1]`, 
But for A01 and A10 due to the central flux, there is information exchange between cells, so `A[0,1]`  and `A[1,0]`   are not equal to `A[0:n, n+1: -1]` and `A[n+1:-1, 0:n]`.

If there is information exchange between cells, is Slate unable to give the correct block?

**Comment by colinjcotter** [comment]
Slate will not give the correct result for non-hybridisable methods. This will happen if the form involves products of test function from one side and trial function from the other, like you have.

On 28 Jul 2022, at 16:04, Sean ***@***.***> wrote:

﻿

I use LDG method + Backward Euler to solve the heat equation (PeriodicRectangleMesh), then get the matrix
$\begin{pmatrix}A_{00} &amp; A_{01} \\ A_{10} &amp; A_{11} \end{pmatrix} \begin{pmatrix} U \\ P \end{pmatrix} = \begin{pmatrix} F \\0 \end{pmatrix}$

This can be transformed into solving the following system of linear equations
$\left(A_{00} - A_{01} ( A_{11}^{-1} A_{10})\right) U = F$

I use Slate to achieve as follows:

....
DG = FunctionSpace(mesh, "DG", Pk)
DG_Vec = VectorFunctionSpace(mesh, "DG", Pk)
MixedSpace = DG * DG_Vec

u_trial, q_trial = TrialFunctions(MixedSpace )
v, w = TestFunctions(MixedSpace )

u_flux = avg(u_trial)
q_flux = avg(q_trial)
A00 = u_trial*v*dx
A01 = - dtc*(-dot(q_trial,grad(v))*dx + dot(q_flux,jump( v,n))*dS )
A11 = dot(q_trial,w)*dx
A10 = - (-u_trial*div(w)*dx + u_flux*jump(w,n)*dS)
LHS = A00 +A01 + A10 + A11

RHS = u*v*dx

# Slate
A = Tensor(LHS).blocks
a_new = A[0,0] - A[0,1] * A[1,1].inv * A[1,0]
RHS_Tensor = Tensor(RHS).blocks
b_new = RHS_Tensor[0]

u_solution = Function(DG)

while (t < FinalTime ):
    a_m = assemble(a_new)
    b_m = assemble(b_new)

    solve(a_m, u_solution, b_m)
    u.assign(u_solution)

But the result is wrong now.

So I check the block A00, A01, A10 and A11.
A00 and A11 are the mass matrix(No information exchange between different cells), so A[0,0] and A[1,1] are equal to A[0:n, 0:n] and A[n+1:-1, n+1:-1],
But for A01 and A10 due to the central flux, there is information exchange between cells, so A[0,1] and A[1,0] are not equal to A[0:n, n+1: -1] and A[n+1:-1, 0:n].

If there is information exchange between cells, is Slate unable to give the correct block?
