### ISSUE TITLE
Problem on installation

### ISSUE THREAD

**Issue by cjunho** [firedrakeproject/firedrake#2519]
I tried to install Firedrake on my server machine, but I failed to install.

My server is 
IBM x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0.

The OS is
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

The log files are as follows
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/9283377/firedrake-install.log)
[firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/9283378/firedrake-update.log).

What caused the problem and how can I fix it?

**Comment by connorjward** [comment]
`firedrake-install.log` gives the error message:
```
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Cannot build Bison. It requires either "flex" or "lex" in PATH. Please install flex and retry.
Or disable Bison with --with-bison=0
*******************************************************************************
```

Bison is listed as a [system requirement](https://firedrakeproject.org/download.html#system-requirements) for Firedrake so should be installed right at the start of the installation. However, I also see the line:

```
2022-08-06 01:55:50,112 INFO   apt-get not found or disabled. Proceeding on the rash assumption that your compiled dependencies are in place.
```

I think the solution here is:
- Figure out why `apt-get` is not working (e.g. what happens if you run `sudo apt-get install bison`)
- If you get it working, then delete the existing `firedrake` directory and restart `firedrake-install`.
- If you don't, find another way to install the system requirements and then run `python3 firedrake-install --no-package-manager`

Lastly, I also notice that you are using an Anaconda version of Python (`/home/anaconda3/bin/python`). This is listed as an anti-requirement [here](https://firedrakeproject.org/download.html#system-anti-requirements) so please find an alternative Python to use.
