### ISSUE TITLE
 A problem appear when  interpolate the constant value to the DG functionspace

### ISSUE THREAD

**Issue by tu1620808124** [firedrakeproject/firedrake#2520]
if k in region (70<=x<=100 and 0<=y<=100) or (150<=x<=180 and 50<=y<=150) is 1.e-12,otherwise 1.e-10 
>K = conditional(Or(And(And(ge(x, 70.0), le(x, 100.0)) , And(ge(y, 0.0), le(y, 100.0))), And(And(ge(x, 150.0), le(x, 180.0)), And(ge(y, 50.0),le(y, 150.0)))), Constant(1.e-12), Constant(1.e-10))
> V = FunctionSpace(mesh, "DG",1)
>K = interpolate(K, V)
when I choose DG(0) functionspace , everything is ok， the distribution of k is:
![1660100506302](https://user-images.githubusercontent.com/49664375/183801421-c6f638fb-dc4f-4a2b-acc5-8407f0aec7b7.png)

but when using the DG(1), almost region is ok, except for the negative value  at the white line(to show the line I use the different color range from the front):
![k](https://user-images.githubusercontent.com/49664375/183801841-16bd595b-7937-4428-ad13-17d148c02dbe.png)
and , when i change interpolate to project , There are also problems.

**Comment by dham** [comment]
Looks like roundoff to me. Interpolating into DG is always a somewhat problematic game. It's a little difficult to tell you exactly what is going on because you haven't included all of your code. Please provide the full code for a minimal failing example (for example I can't see from this whether you are using triangle or quadrilateral cells, and that too makes a difference).

One of the things you can do to improve the robustness of interpolating piecewise constant functions is to first interpolate into DG0 and then project from there into the space you actually want.

**Comment by tu1620808124** [comment]
Here's my code. As you said, I first interpolate into DG0 and then interpolate into DG1, which can get the right results.
> from firedrake import*
mesh = RectangleMesh(100, 50, 300, 150, quadrilateral = True)
V = FunctionSpace(mesh, "DG", 1)
x, y = SpatialCoordinate(mesh)
K = conditional(Or(And(And(ge(x, 70.0), le(x, 100.0)) , And(ge(y, 0.0), le(y, 100.0))), And(And(ge(x, 150.0), le(x, 180.0)), And(ge(y, 50.0),le(y, 150.0)))), Constant(1.e-12), Constant(1.e-10))
K_ = interpolate(K, V)
#K_ = project(K, V)
File("permeability.pvd").write(K_)

**Comment by dham** [comment]
What you're observing here is actually an artifact of the process of visualisation. If I run your code and check the values of the coefficients of the Function `K_`, I find that they are all exactly 1.e-10 or 1.e-12. 
```python
In [11]: np.count_nonzero(K_.dat.data == 1.e-10)
Out[11]: 17320

In [12]: np.count_nonzero(K_.dat.data == 1.e-12)
Out[12]: 2680

In [14]: len(K_.dat.data)
Out[14]: 20000
```
However, Firedrake by default uses the Gauss-Lobatto points as DG nodes on quadrilaterals. VTK uses equispaced points. This means that we need to change basis in order to output to VTK. Under the hood, Firedrake is effectively doing the following:
```python
fe = FiniteElement("DQ", mesh.ufl_cell(), 1, variant="equispaced")
V_ = FunctionSpace(mesh, fe)
Kv = interpolate(K_, V_)
```
That change of basis involves floating point operations that will have roundoff errors. If I look at the minimal coefficient value of Kv, I get:
```python
In [18]: Kv.dat.data.min()
Out[18]: -8.473651497465943e-11
```
Which lines up with what you observe. This isn't really wrong: roundoff error is an inherent part of floating point arithmetic.

You could use equispaced elements in your finite element calculation (just create your FunctionSpace as above) and then you won't see this anomaly on output. However, you probably don't want to do that because it will make your finite element problem a little less well conditioned.
