### ISSUE TITLE
Rename split (`.split` -> `.subfunctions`)

### ISSUE THREAD

**Issue by JDBetteridge** [firedrakeproject/firedrake#2623]
We should rename split from `.split` -> `.subfunctions`.

Someone should pick this up at some point

**Comment by uygarkov** [comment]
Hello, my name is Uygar. I am a master student at University of Stuttgart. 

As a term project of my course [Simulation Software Engineering](https://simulation-software-engineering.github.io/homepage/) , we were assigned to make a contribution to the open-source simulation softwares. Since I am interested in Finite Element Method, I wanted to work on the Firedrake project.

The type of contribution is up to us, but we are learning how to use Git tools, documentate, use containers, package softwares. I am quite new to Software Engineering but I have worked on Python before so I would like to work on this issue (or any other issue that you can recommend) after discussing it with my professors. Have a nice year! 

Uygar Kovanci

**Comment by JDBetteridge** [comment]
Hi @uygarkov, your contribution would be very welcome. Please feel free to have a go at fixing this issue and opening a PR. If you have any questions feel free to ask, see [here](https://firedrakeproject.org/contact.html) for contacting the team. The slack channel is very active.

**Comment by connorjward** [comment]
@uygarkov I think the things that need doing are:
- Rename the current `.split` function to `.subfunctions` (in `function.py` I think but check everywhere for it).
- Write a `.split` function that looks something like:
```py
def split(self):
  import warnings
  warnings.warn(DeprecationWarning, <informative message>)
  return self.subfunctions
```
- Check through all the documentation and notebooks to make sure that we don't call `.split` anywhere.

**Comment by wence-** [comment]
> ```python
> def split(self):
>   import warnings
>   warnings.warn(DeprecationWarning, <informative message>)
>   return self.subfunctions
> ```

Per https://docs.python.org/3/library/warnings.html#warning-categories

for user-facing warnings one should prefer `FutureWarning` over `DeprecationWarning`.
