### ISSUE TITLE
Strange gradient result

### ISSUE THREAD

**Issue by ColCom** [firedrakeproject/firedrake#2935]
When I calculate the gradient of a straight interface in Firedrake I get a somewhat strange result, the same code in Fenics seems more accurate. Where does this difference come from?

`from firedrake import *

Nx, Ny = 40, 60
lx, ly = 1.6, 2.2
mesh = RectangleMesh(Nx, Ny, lx, ly, diagonal="crossed")

V = FunctionSpace(mesh, "DG", 1)
x, y = SpatialCoordinate(mesh)

expr = -1+(x>0.71)*2
phi = Function(V).interpolate(expr)

quiver(grad(phi))
`
![grad](https://github.com/firedrakeproject/firedrake/assets/78821979/903f0092-dfd1-4c1d-8435-2fcc1135103c)

Fenics code:

`from dolfin import *

Nx, Ny = 40, 60
lx, ly = 1.6, 2.2
mesh = RectangleMesh(Point(0.0, 0.0), Point(lx, ly), Nx, Ny, "crossed")

V = FunctionSpace(mesh, 'DG', 1)

phi = interpolate(Expression('x[0]>0.71', degree=1), V)

plot(grad(phi))`

**Comment by ksagiyam** [comment]
I think we can obtain the result you are expecting by defining `expr = (x > 0.69) * 0.5 + (x > 0.71) * .5`, i.e., you will need to set correct values on vertices at the center of `"crossed"` rectangles; see the vertex labeled `4` at https://github.com/firedrakeproject/firedrake/blob/dd124559faea36918bed173c73693ab9d1f825e5/firedrake/utility_meshes.py#L675
I do not know how FEniCS handles crossed rectangular mesh.

**Comment by stephankramer** [comment]
Just to expand a little: the reason you are getting "strange results" is that in the cells that straddle the jump at x=0.71 the nodes 0, 2 and 4 (again see the diagram) are to the left of the jump and take the value -1, and nodes 1 and 3 take the value +1. This means that the 4 triangles all end up with a different gradient, including skew gradients in the top and bottom triangles. For plotting purposes, in quiver the gradient is interpolated to the vertices (P1 CG) but since the gradient may be different in the triangles adjacent to the vertices, which vector gets chosen is arbitrary and depends on the ordering of the mesh. I suspect Fenics does the same, but just has a different ordering and it so happens that fewer of these skew gradient vectors get chosen (note they're still there near the boundaries)

**Comment by ColCom** [comment]
Thanks,  for the quick responses. Great answer. I didn't realize the gradient is interpolated to (P1 CG) for the quiver plot.  Now it makes sense to me.
