### ISSUE TITLE
Garbage collection improvements

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#3075]
A couple of places have been identified where our garbage collection could be improved:

- We should call `gc.collect` before we call `PETSc.garbage_cleanup`. Otherwise we get apparent memory leaks since we only clean up objects once Python decides to break the reference cycles.
- We should add our own `garbage_cleanup` routine for users to call. This should take a user-level comm object and extract the internal PyOP2 comm where the objects are actually being stored for deletion.

**Comment by jrmaddison** [comment]
A full collection via `gc.collect()` can be pretty expensive.

**Comment by dham** [comment]
> A full collection via `gc.collect()` can be pretty expensive.

At this stage we're still dealing with the corner cases where we're not collecting enough. Once we get to the point where we have observable performance hits in the wild, the plan is to code a back-off strategy under which the actual collection occurs at most every n seconds (its a little more subtle than that because it has to be collective, but that's the idea)
