### ISSUE TITLE
DOCS: Notebooks adjoint

### ISSUE THREAD

**Issue by Ig-dolci** [firedrakeproject/firedrake#3088]
**Issue**
Adjoint notebooks fail when the notebook is executed more than once without restarting the Kernel.

**Where to find**
Where to find this failure:
https://github.com/firedrakeproject/firedrake/blob/master/docs/notebooks/06-pde-constrained-optimisation.ipynb
https://github.com/firedrakeproject/firedrake/blob/master/docs/notebooks/11-extract-adjoint-solutions.ipynb

**Possible solution**
I added `pause_annotation()` on the latest notebook cell, which fixed this failure. Is that a better solution?

**Comment by connorjward** [comment]
In general the adjoint shouldn't play well with notebooks due to the possibilities for out-of-order execution. However for this case would it be sufficient to reset the tape in one of the uppermost cells? That would also be a convenient place to warn the user about the perils of running the cells in the wrong order.

**Comment by Ig-dolci** [comment]
I tried 
```
     get_working_tape().clear_tape()
     get_working_tape().reset_blocks()
```
That was not sufficient to fix this failure.  

I agree with you about the warning.

**Comment by connorjward** [comment]
I think I found a solution. If you replace `continue_annotating()` at the top of the notebook with

```py
if not annotate_tape():
    continue_annotation()
```

then it seems to work. I think this is because of the way annotation is [tracked with an integer rather than a boolean](https://github.com/dolfin-adjoint/pyadjoint/blob/master/pyadjoint/tape.py#L12) so calling `continue_annotation()` twice actually breaks things.

**Comment by ReubenHill** [comment]
> I think I found a solution. If you replace `continue_annotating()` at the top of the notebook with
> 
> ```python
> if not annotate_tape():
>     continue_annotation()
> ```
> 
> then it seems to work. I think this is because of the way annotation is [tracked with an integer rather than a boolean](https://github.com/dolfin-adjoint/pyadjoint/blob/master/pyadjoint/tape.py#L12) so calling `continue_annotation()` twice actually breaks things.

That sounds like a bug, did you report it? I can't see anything [here](https://github.com/dolfin-adjoint/pyadjoint/issues) or [here](https://github.com/dolfin-adjoint/dolfin-adjoint/issues)

**Comment by connorjward** [comment]
> > I think I found a solution. If you replace `continue_annotating()` at the top of the notebook with
> > ```python
> > if not annotate_tape():
> >     continue_annotation()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then it seems to work. I think this is because of the way annotation is [tracked with an integer rather than a boolean](https://github.com/dolfin-adjoint/pyadjoint/blob/master/pyadjoint/tape.py#L12) so calling `continue_annotation()` twice actually breaks things.
> 
> That sounds like a bug, did you report it? I can't see anything [here](https://github.com/dolfin-adjoint/pyadjoint/issues) or [here](https://github.com/dolfin-adjoint/dolfin-adjoint/issues)

See https://github.com/dolfin-adjoint/pyadjoint/issues/111

**Comment by Ig-dolci** [comment]
This issue is sorted with pyadjoint  PR [113](https://github.com/dolfin-adjoint/pyadjoint/pull/113)
