### ISSUE TITLE
BUG: Comparing a `Cofunction` to itself via `!=` returns `True`

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/firedrake#3272]
**Describe the bug**
Comparing a `Cofunction` to itself via either `==` or `!=` both return `True`.

**Steps to Reproduce**
```
import firedrake as fd

mesh = fd.UnitIntervalMesh(1)
V = fd.FunctionSpace(mesh, "Discontinuous Lagrange", 0)

phi = fd.Cofunction(V.dual(), name="phi")
assert phi == phi  # Passes
assert not (phi != phi)  # Fails
```

**Expected behavior**
The result from `!=` should be `False`.

**Error message**
No error message.

**Environment:**
Ubuntu 22.04, recent Firedrake build.

**Additional Info**
I'm not sure it's _required_ the result be `False`, but it's what I expected, and it led to some puzzling behaviour in my code.

**Comment by connorjward** [comment]
@nbouziani are you happy to take this on?

**Comment by nbouziani** [comment]
That's a funny one. Your example actually exposes two different problems. First, both checks rely on different implementations, hence the inconsistent results. I fixed that in https://github.com/FEniCS/ufl/pull/247. The other thing is that `equals` is currently faulty for cofunctions, which I have just fixed in https://github.com/firedrakeproject/firedrake/pull/3274.

I think this can be closed now. @jrmaddison thanks for spotting it
