### ISSUE TITLE
BUG: $VIRTUAL_ENV/.cache not created

### ISSUE THREAD

**Issue by ksagiyam** [firedrakeproject/firedrake#3353]
**Describe the bug**
$VIRTUAL_ENV/.cache is not created with the latest version of Firedrake.

Can reproduce with the latest firedrake-vanilla docker image.

**Steps to Reproduce**
Run `firedrake-clean` and run anything, e.g:
```
from firedrake import *


mesh = UnitIntervalMesh(1)
V = FunctionSpace(mesh, "CG", 1)
f = Function(V)
assemble(f * dx)
```

**Environment:**
Latest docker image

**Additional Info**
Seems to have been caused by [this PR](https://github.com/firedrakeproject/firedrake/pull/3152)

**Comment by JDBetteridge** [comment]
Can you comment on why you think it is that PR specifically, please?

**Comment by connorjward** [comment]
Oh. I have encountered a bug with the same PR. Specifically what is wrong here is the PR adds a `from pyop2 import mpi` to `petsc.py` ([code](https://github.com/firedrakeproject/firedrake/pull/3152/file)). This is an issue [as noted in `__init__.py`](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/__init__.py#L58):
```py
# Set up the cache directories before importing PyOP2.
firedrake_configuration.setup_cache_dirs()
```

This now happens *after* importing PyOP2 because we import `firedrake.petsc` right at the start.

I have a fix for my particular issue (logging) [here](https://github.com/firedrakeproject/firedrake/pull/3351) but something more general is needed to fix the cache dir issue.

**Comment by JDBetteridge** [comment]
I am unable to reproduce the issue either locally or in a docker container by clearing the cache `firedrake-clean` and running the quick tests `pytest tests/regression/ -k "poisson_strong or stokes_mini or dg_advection"`.
