### ISSUE TITLE
Create a Zenodo release for M4R project. 

### ISSUE THREAD

**Issue by emmarothwell1** [firedrakeproject/firedrake#3621]
Could you please create a Zenodo release for my M4R project?:

### Implementing a restricted function space class in Firedrake. 

Here is the json file: 
[firedrake.json](https://github.com/user-attachments/files/15747620/firedrake.json)

Thank you! :)

**Comment by ksagiyam** [comment]
Your branch of firedrake no longer exists as, once PR is merged, the source branch is automatically deleted. As your code is already in `master`, you can make the `firedrake.json` file with `master` checked out for all packages. Or just post whatever you passed to `--info-file` here, so that I can do that.

**Comment by emmarothwell1** [comment]
Sorry about that, here's the updated one with the main branch checked out:
[firedrake.json](https://github.com/user-attachments/files/15748078/firedrake.json)

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20240609.0`
DOI is 10.5281/zenodo.11529542
Zenodo URL is https://zenodo.org/record/11529542
BibTeX

```bibtex
@misc{zenodo/Firedrake-20240609.0,
 key   = {zenodo/Firedrake-20240609.0},
 title = {{Software used in `Implementing a restricted function space class in Firedrake'}},
 year  = {2024},
 month = {jun},
 doi   = {10.5281/zenodo.11529542},
 url   = {https://doi.org/10.5281/zenodo.11529542},
}

```
Done. Thanks!
