### ISSUE TITLE
FFC returning empty kernels on mixed function space

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#509]
I'm occasionally seeing errors due to empty kernel trees. Isolated 2 examples below. Possibly related to #483. EDIT: fixed spilt() functions.

Test 1: split mass matrix
```
from firedrake import *

mesh = UnitSquareMesh(10,10)
U = VectorFunctionSpace(mesh, 'DG', 1)
H = FunctionSpace(mesh, 'CG', 2)
W = MixedFunctionSpace([U, H])

f = Function(H)
sol = Function(W)
u, eta = split(sol)
f.interpolate(Expression('-x[0]'))

test = TestFunction(W)
test_U, test_H = TestFunctions(W)

# NOTE fails
F = inner(u, test_U)*dx + inner(eta, test_H)*dx + inner(grad(f), test_U)*dx

# NOTE works
#F = inner(sol, test)*dx + inner(grad(f), test_U)*dx

prob = NonlinearVariationalProblem(F, sol)
solver = NonlinearVariationalSolver(prob)
solver.solve()
print sol.split()[0].dat.data.max()
```

Test 2: DG with interface terms
```
from firedrake import *

mesh = UnitSquareMesh(10,10)
U = VectorFunctionSpace(mesh, 'DG', 1)
H = FunctionSpace(mesh, 'CG', 2)
W = MixedFunctionSpace([U, H])

f = Function(H)
sol = Function(W)
u, eta = split(sol)
f.interpolate(Expression('-x[0]'))

test = TestFunction(W)
test_U, test_H = TestFunctions(W)
normal = FacetNormal(mesh)

F = (inner(sol, test)*dx - inner(f, div(test_U))*dx
     + avg(f)*jump(normal, test_U)*dS + f*inner(normal, test_U)*ds)

prob = NonlinearVariationalProblem(F, sol)
solver = NonlinearVariationalSolver(prob)
solver.solve()
print sol.split()[0].dat.data.max()
```

Both fail with the error
```
Traceback (most recent call last):
  File "empty_kernels1.py", line 46, in <module>
    solver = NonlinearVariationalSolver(prob)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/variational_solver.py", line 100, in __init__
    ctx = solving_utils._SNESContext(problem)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/solving_utils.py", line 105, in __init__
    for problem in problems)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/solving_utils.py", line 105, in <genexpr>
    for problem in problems)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/assemble.py", line 67, in assemble
    inverse=inverse, nest=nest)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/assemble.py", line 100, in _assemble
    inverse=inverse)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/ffc_interface.py", line 284, in compile_form
    ((kernel, needs_orientations), ) = ffc_kernel.kernels
ValueError: need more than 0 values to unpack
```

**Comment by wence-** [comment]
Aha, you've actually run into not a relation of #483 but rather #407.  You wanted to use:

```
u, eta = split(sol)
```

rather than

```
u, eta = sol.split()
```

The former gives you a UFL `Indexed` object that is suitable for use in a form, the latter just gives you the subfunction directly which you can use for output and so forth, but when you use it in a form UFL doesn't know that it comes from the split function.  So what's actually happening is you have:

```
F = inner(u, test)*dx + ...
```
And when we compute the derivative of F wrt sol to get the Jacobian we get an empty form back, since UFL doesn't know that u is a component of sol.

This distinction is somewhat annoying, however, it's unfortunately not that trivial to fix.

**Comment by wence-** [comment]
Aha, you've actually run into not a relation of #483 but rather #407.  You wanted to use:

```
u, eta = split(sol)
```

rather than

```
u, eta = sol.split()
```

The former gives you a UFL `Indexed` object that is suitable for use in a form, the latter just gives you the subfunction directly which you can use for output and so forth, but when you use it in a form UFL doesn't know that it comes from the split function.  So what's actually happening is you have:

```
F = inner(u, test)*dx + ...
```
And when we compute the derivative of F wrt sol to get the Jacobian we get an empty form back, since UFL doesn't know that u is a component of sol.

This distinction is somewhat annoying, however, it's unfortunately not that trivial to fix.

**Comment by wence-** [comment]
Aha, you've actually run into not a relation of #483 but rather #407.  You wanted to use:

```
u, eta = split(sol)
```

rather than

```
u, eta = sol.split()
```

The former gives you a UFL `Indexed` object that is suitable for use in a form, the latter just gives you the subfunction directly which you can use for output and so forth, but when you use it in a form UFL doesn't know that it comes from the split function.  So what's actually happening is you have:

```
F = inner(u, test)*dx + ...
```
And when we compute the derivative of F wrt sol to get the Jacobian we get an empty form back, since UFL doesn't know that u is a component of sol.

This distinction is somewhat annoying, however, it's unfortunately not that trivial to fix.

**Comment by wence-** [comment]
Aha, you've actually run into not a relation of #483 but rather #407.  You wanted to use:

```
u, eta = split(sol)
```

rather than

```
u, eta = sol.split()
```

The former gives you a UFL `Indexed` object that is suitable for use in a form, the latter just gives you the subfunction directly which you can use for output and so forth, but when you use it in a form UFL doesn't know that it comes from the split function.  So what's actually happening is you have:

```
F = inner(u, test)*dx + ...
```
And when we compute the derivative of F wrt sol to get the Jacobian we get an empty form back, since UFL doesn't know that u is a component of sol.

This distinction is somewhat annoying, however, it's unfortunately not that trivial to fix.

**Comment by wence-** [comment]
Aha, you've actually run into not a relation of #483 but rather #407.  You wanted to use:

```
u, eta = split(sol)
```

rather than

```
u, eta = sol.split()
```

The former gives you a UFL `Indexed` object that is suitable for use in a form, the latter just gives you the subfunction directly which you can use for output and so forth, but when you use it in a form UFL doesn't know that it comes from the split function.  So what's actually happening is you have:

```
F = inner(u, test)*dx + ...
```
And when we compute the derivative of F wrt sol to get the Jacobian we get an empty form back, since UFL doesn't know that u is a component of sol.

This distinction is somewhat annoying, however, it's unfortunately not that trivial to fix.

**Comment by tkarna** [comment]
Argh, thanks for pointing that out, it makes perfect sense.

In my production code I'm using ```split(sol)``` though, and I do see an empty kernel issue. I'll dig in deeper to see what's going on.

**Comment by wence-** [comment]
There are plausibly reasons when this could happen, I think.

Can you try with the following patch:

```patch
diff --git a/firedrake/ffc_interface.py b/firedrake/ffc_interface.py
index e92a50e..e8d92a2 100644
--- a/firedrake/ffc_interface.py
+++ b/firedrake/ffc_interface.py
@@ -188,6 +188,8 @@ class FFCKernel(DiskCached):
         inc = [path.dirname(__file__)]
         try:
             ffc_tree = ffc_compile_form(form, prefix=name, parameters=parameters)
+            if len(ffc_tree) == 0:
+                raise EmptyIntegrandError
             kernels = []
             # need compute_form_data here to get preproc form integrals
             fd = compute_form_data(form)
```

**Comment by tkarna** [comment]
That patch seems to work. The model runs and results look plausible. But I've no idea which term causes the issue.

**Comment by tkarna** [comment]
I do believe test 2 fails with the recent update c068dac.

**Comment by tkarna** [comment]
Test 2 still fails with latest updates. The patch doesn't help. Could you please confirm?

**Comment by wence-** [comment]
I see the following backtrace:

```python
  File "/data/lmitche1/src/PyOP2/pyop2/host.py", line 58, in _ast_to_c
    ast_handler.plan_cpu(self._opts)
  File "/data/lmitche1/src/deps/COFFEE/coffee/plan.py", line 390, in plan_cpu
    loop_opts = _generate_cpu_code(self, kernel, **params)
  File "/data/lmitche1/src/deps/COFFEE/coffee/plan.py", line 226, in _generate_cpu_code
    loop_opt.rewrite(rewrite)
  File "/data/lmitche1/src/deps/COFFEE/coffee/optimizer.py", line 93, in rewrite
    ew.expand()
  File "/data/lmitche1/src/deps/COFFEE/coffee/rewriter.py", line 204, in expand
    dimension = max(occurrences.iteritems(), key=operator.itemgetter(1))[0]
ValueError: max() arg is an empty sequence
```

With the patch applied.  If I run with `parameters["coffee"]["O2"] = False`, then I get a plausibly correct result.  Is this the error you're seeing?  This looks to be a bug in coffee's expansion rewriting, but I don't quite understand it.

**Comment by tkarna** [comment]
With the patch above I get the empty kernel issue:
```
Traceback (most recent call last):
  File "empty_kernels2.py", line 70, in <module>
    solver = NonlinearVariationalSolver(prob)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/variational_solver.py", line 100, in __init__
    ctx = solving_utils._SNESContext(problem)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/solving_utils.py", line 105, in __init__
    for problem in problems)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/solving_utils.py", line 105, in <genexpr>
    for problem in problems)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/assemble.py", line 67, in assemble
    inverse=inverse, nest=nest)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/assemble.py", line 100, in _assemble
    inverse=inverse)
  File "/home/tuomas/.local/lib/python2.7/site-packages/firedrake/ffc_interface.py", line 290, in compile_form
    ((kernel, needs_orientations), ) = ffc_kernel.kernels
ValueError: need more than 0 values to unpack
```

If I patch with
```
diff --git a/firedrake/ffc_interface.py b/firedrake/ffc_interface.py
index 02c4053..199868c 100644
--- a/firedrake/ffc_interface.py
+++ b/firedrake/ffc_interface.py
@@ -283,7 +283,7 @@ def compile_form(form, name, parameters=None, inverse=False):
             ffc_kernel = FFCKernel(f, name + str(i) + str(j), parameters)
             # FFC noticed the integrand was zero, so don't bother
             # using this kernel (it's invalid anyway)
-            if ffc_kernel._empty:
+            if ffc_kernel._empty or len(ffc_kernel.kernels)==0:
                 continue
             ((kernel, needs_orientations), ) = ffc_kernel.kernels
             # need compute_form_data here to get preproc integrals
```
I get the same error as you. If I run with ```parameters["coffee"]["O2"] = False```, I get the correct solution.

**Comment by wence-** [comment]
Thanks, I think I've now spotted the problem (you can follow along in coneoproject/COFFEE#47), but I'll update here when fixed.  The empty kernel issue will necessitate a firedrake-side change I guess.

**Comment by wence-** [comment]
In reference to the masking of a bug, I believe there are legitimate reasons why one might get an empty kernel list here.  Essentially, UFL does some zero-simplification, but it's not complete.  When we see a form on a mixed space we split it up and "multiplication-by-zero" turns out to be hidden inside terms that are not zero-simplified.  However, FFC does a deeper analysis and so does notice that the term can be zero, hence returning an empty list.

**Comment by tkarna** [comment]
OK good to know, I'll keep using the patch.
Test 2 runs now with fixed FFC and the patch above.

**Comment by wence-** [comment]
OK, this should now be fixed, as I've merged the above patch and the FFC changes have landed, closing for now.
