### ISSUE TITLE
Autocaching projects

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#589]
calling

    u.project(myform)

is a very common operation, that often forms part of a timestepping algorithm and so is repeated. Currently, project sets up a new solver each time, making this slow, and it gets very messy to hand-write solvers for this.

How about a project cache that stores the solvers, with a tag created from u and myform?

**Comment by dham** [comment]
OK:

a) What does DOLFIN do in this case (compatibility is important).

b) If DOLFIN doesn't handle this. I wonder if the Right Thing might be to
have a Projector object in a manner analogous to a LinearVariationalSolver

**Comment by colinjcotter** [comment]
a) What does DOLFIN do in this case (compatibility is important).
>

Nothing, I think.


>
> b) If DOLFIN doesn't handle this. I wonder if the Right Thing might be to
> have a Projector object in a manner analogous to a LinearVariationalSolver
>

Yes, that would be good.

--cjc

**Comment by miklos1** [comment]
Caching should never be the first option to consider when encountering a performance problem. While it might be the right answer in some cases, the tendency to apply caching first for all performance problems leads to intense side-effects, such as:
- caching bugs, since cache invalidation is hard to do correctly in all cases.
- difficulty in testing, when a code path isn't exercised but rather the result is returned from cache.
- difficulty in benchmarking, when a code path isn't exercised but rather the result is returned from cache.

To say something about the concrete issue: I would prefer an explicit Projector object as opposed to automatic caching.

**Comment by wence-** [comment]
Fixed in #686 by introducing a `Projector` object, thanks Colin.
