### ISSUE TITLE
Creating OuterProductElements on quad meshes fails

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#596]
Creating, for example, RT1 on quad meshes fails because the cell is a quad, not an product of intervals.

Minimal failing example:

```python
from firedrake import *

m = UnitSquareMesh(2, 2, quadrilateral=True)

u0 = FiniteElement("CG", interval, 1)
u1 = FiniteElement("DG", interval, 0)
RT1 = HDiv(OuterProductElement(u0, u1)) + HDiv(OuterProductElement(u1, u0))
V1 = FunctionSpace(m, RT1)
```

**Comment by miklos1** [comment]
This is by design. An extruded interval is a quad with a special direction, thus all finite elements on quads work on extruded interval, but the reverse is not true.

To create the RT1 element on quads, do:
```
from firedrake import *

m = UnitSquareMesh(2, 2, quadrilateral=True)

RT1 = FiniteElement("RTCF", quadrilateral, 1)
V1 = FunctionSpace(m, RT1)
```

If you want to share code for the the fully unstructured and the extruded version, you can do:
```
RT1 = FiniteElement("RTCF", m.ufl_cell(), 1)
V1 = FunctionSpace(m, RT1)
```
or simply:
```
V1 = FunctionSpace(m, "RTCF", 1)
```
