### ISSUE TITLE
Testing on Travis+Mac often times out

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#653]
In particular, building OpenMPI and PETSc takes quite some time. While execution times on Travis are somewhat random, in many cases the Mac test reaches 50 minutes when Travis shuts it down.

**Comment by dham** [comment]
There are two potential solutions to this. A partial solution will occur when Brew fix the OpenMPI issue. The other part of the issue is that we ought to use travis' caching capabilities to cache the build of PETSc. I have ideas about how to do this (it requires a little hackery) but it's not at the top of my stack.

**Comment by wence-** [comment]
Fixed because homebrew fixed openmpi.  Build caching on mac builders is not yet enabled on travis, but will automatically start working when it does (the install script handles caching, it's just that the upload/download of caches on macs is not there).  So I think this is fixed.
