### ISSUE TITLE
Add SLEPc to install script

### ISSUE THREAD

**Issue by juan42** [firedrakeproject/firedrake#738]
As you may know, SLEPc is an eigenvalue solver library build on PETSc. It would be convenient to add it to the installer script.

The manual installation process looks like this in an activated firedrake virtualenv:

```shell
(firedrake) $ git clone https://bitbucket.org/slepc/slepc.git
(firedrake) $ cd slepc; python setup.py install; cd ..
(firedrake) $ git clone https://bitbucket.org/slepc/slepc4py.git
(firedrake) $ cd slepc4py; python setup.py install; cd ..
```
The virtualenv path is honoured automatically.

I'm working on a patch for the installer, but wanted to propose the enhancement here first.

**Comment by wence-** [comment]
Done in #748.  Thanks!

**Comment by francispoulin** [comment]
I recently tried using slepc with firedrake and it didn't work.  I guess these lines above are not done by default?

I sent into my firedrake directory and ran the above lines and I find that there is now slepc and slepc4py folders that are present, but when I open firedrake these are not found.

A couple of questions:

1) Should slepc automatically be a part of firedrake?  Since I don't have it I'm guessing no.

2) If I wanted to install slepc, then I presume I should do the above but where should I run the lines or where do I copy the folders?

Thanks in advance.

**Comment by dham** [comment]
Hi Francis,

The way that you install slepc in Firedrake is by passing the --slepc option to firedrake-update or firedrake-install as appropriate:
```
firedrake-update --slepc
```
If you have checked out your own versions of slepc in the firedrake src directory, this may cause the firedrake installation of slepc to fail, so you should remove those first.

**Comment by francispoulin** [comment]
Thanks for the quick reply.  That makes a lot of sense.

I removed the damage that I might have started yesterday and installed it 

firedrake-update --slepc --honour-pythonpath

and it seemed to work.  But I noticed that when it finds the dependencies it finds petsc, petsc4py but not slepc and slepc4py.  

The directories are created in my firedrake folder but then when I try following test_slepc.py I can seem to import SLEPc.  The error is below.

Any idea what might have gone wrong?

>>> from slepc4py import SLEPc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fpoulin/software/firedrake/local/lib/python2.7/site-packages/slepc4py/SLEPc.py", line 4, in <module>
    SLEPc = ImportSLEPc(ARCH)
  File "/home/fpoulin/software/firedrake/local/lib/python2.7/site-packages/slepc4py/lib/__init__.py", line 34, in ImportSLEPc
    return Import('slepc4py', 'SLEPc', path, arch)
  File "/home/fpoulin/software/firedrake/local/lib/python2.7/site-packages/petsc4py/lib/__init__.py", line 64, in Import
    module = imp.load_module(fullname, fo, fn, stuff)
ImportError: /home/fpoulin/software/firedrake/local/lib/python2.7/site-packages/slepc/lib/libslepc.so.3.07: undefined symbol: petscinitializenoarguments_

**Comment by dham** [comment]
I'm afraid I am unable to reproduce this issue. firedrake-update --slepc worked for me. I have a couple of queries though:

1. Why are you using honour-pythonpath? This shouldn't usually be necessary.
2. It's possible you have stale libraries around from your previous attempts with slepc. Try:
```
firedrake-update --clean --rebuild
```
or even, failing that, a fresh Firedrake install.

**Comment by francispoulin** [comment]
Thanks! 

I did the clean rebuild you suggested and that seemed to do the trick.

The reason why I need to honour-pythonpath because I have PYTHONPATH defined.  If I don't honour the path it won't do anything.  I could remove this one path but I use it for other thing so would like to keep it around.  

Now to compute eigenvalues!
