### ISSUE TITLE
Moving meshes requires reset of spatial_index for correct point evaluation

### ISSUE THREAD

**Issue by danielru** [firedrakeproject/firedrake#793]
The attached example used the `.at` evaluation routine provided by `Function` objects to transfer information from a moving to a stationary mesh. As pointed out by Lawrence over the emailing list, this requires calling

`del meshA.spatial_index`

to work properly. It might be helpful to add this functionality to the API. 

If possible, it might be nice to also have a `moveMesh` function or something similar that hides code like

`Vc    = meshA.coordinates.function_space()`
`f2    = Function(Vc).interpolate(Expression(("x[0]-0.5","x[1]+2.0")))`
`meshA.coordinates.assign(f2)`

See here: [here](http://www.firedrakeproject.org/mesh-coordinates.html)

[example.zip](https://github.com/firedrakeproject/firedrake/files/290836/example.zip)

**Comment by wence-** [comment]
Invalidating the cache is straightforward to add:

```python
class MeshTopology(...):
    

    def clear_spatial_index(self):
        try:
            del self.spatial_index
        except AttributeError:
            pass
```

I think the `move_mesh` idea is a good idea.  What should the API be?  I can think of two circumstances.

1. Moving the coordinates of an existing mesh
2. Replacing the function space for the coordinates (and moving).

I think moving the mesh should only cover the former.  Which suggests it can just be a method on a mesh (since it doesn't return a new mesh).

something like:

```python

def move(self, expr_or_function):
    if isinstance(expr_or_function, Function):
        self.coordinates.assign(expr_or_function)
    else:
        tmp = Function(self.coordinates.function_space()).interpolate(expr_or_function)
        self.coordinates.assign(tmp)
    self.clear_spatial_index()
```

**Comment by miklos1** [comment]
Spatial index should live on the mesh geometry, not mesh topology.

**Comment by wence-** [comment]
That's true. But moving it doesn't fix this bug

**Comment by ANaumann85** [comment]
I tried the evaluation on a moving mesh using the firedrake-install from yesterday (August 15th). This time, there is a small numerical error, as can be seen by the appended test case.
My mesh moves from 0.2 to units in negative y-direction in 5 steps. Before each movement, I create a new Function u_A and interpolate some values in the lines 20 and 21 respectively. 
After that, I try to evaluate at (0, 2.2), which resides in the mesh in all iterations. But the  function call
 u_A.at(0.0, 2.2) returns the correct value only in the first iteration. Every later iteration, it returns a None, i.e. it does not find the point.
Furthermore, the evaluation at the same y-coordinate, but a slightly shifted x-coordinate works, see line 25 in the appended test.
This behavior is interesting, because we move the mesh in x and y direction once (see line 16). After this movement, we find the value at the point (0.0, 2.2). All further movements only effect the y-direction, so the x coordinate values should not change at all.
[moving_mesh_test_short.zip](https://github.com/firedrakeproject/firedrake/files/420118/moving_mesh_test_short.zip)
