### ISSUE TITLE
Firedrake installation failure on Mac OS X Yosemite 10.10.1(via firedrake-install script)

### ISSUE THREAD

**Issue by CamillaBressan** [firedrakeproject/firedrake#848]
Dear all,

I was following the installation instructions for Firedrake. Unfortunately the script doesn't seem to work on my mac (while on my ubuntu 14.04 works fine).

The final error I get is:
>Traceback (most recent call last):
 > File "firedrake-install", line 929, in <module>
>    install(p+"/")
 > File "firedrake-install", line 524, in install
 >   run_pip_install(["--ignore-installed", package])
  >File "firedrake-install", line 399, in run_pip_install
   > check_call(pipinstall + pipargs)
  >File "firedrake-install", line 223, in check_call
   > log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env))
  >File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
 >   raise CalledProcessError(retcode, cmd, output=output)
>subprocess.CalledProcessError: Command '['/Users/camillabressan/firedrake/bin/pip', 'install', '--no-deps', '-vvv', '--ignore-installed', 'PyOP2/']' returned non-zero exit status 1

Thanks a lot,
Camilla

**Comment by dorugeber** [comment]
Can you run the installation script with logging and attach the log?  The part above only says that the PyOP2 installation failed, which doesn't give much information!

**Comment by CamillaBressan** [comment]
Yes of course, I thought I had included that already. Here's the log.

[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/401030/firedrake-install.txt)

**Comment by dorugeber** [comment]
What is the OSX version?

**Comment by CamillaBressan** [comment]
It's written in the title: Yosemite 10.10.1.

**Comment by dham** [comment]
Hi Camilla, 

The proximate cause of this issue is the Python setup system is trying to use gcc version 4.2 (a truly ancient version from before 2008) as the linker to create a shared library (sparsity.so in this case). Unsurprisingly, gcc 4.2 is not visible in your path which causes the install script to fail.

The Python setup system pulls the programs to use for things like linking from your environment, so we need to find out what in your environment is telling python to use gcc 4.2 for this task. Try the following commands on the command line and see if they turn up any references to gcc or g++ 4.2:

```
echo $LDSHARED
export | grep gcc
export | grep g++
export | grep 4.2
```

**Comment by CamillaBressan** [comment]
Hello,

Thanks for the reply. I tried them but actually no reference comes out, nothing is printed on the shell. I've then tried to set the environment variables CX and CXX to gfortran, and the installation arrives till the end; eventually anyway when I try to import firedrake, I get the message of wrong architecture build.

firedrake/lib/python2.7/site-packages/pyop2/sparsity.so: mach-o, but wrong architecture

**Comment by dham** [comment]
Ah. I suspect setting them to gfortran is the Wrong Thing because all the c/c++ compilation on Mac is usually done with clang, while gfortran really is gcc (because clang doesn't support fortran). Does it work any better if you set CX and CXX (and maybe LDSHARED) to clang?

**Comment by CamillaBressan** [comment]
Seems not. And I get two different error messages for LDSHARED set to clang or not.
Here the log file in the first case:

[firedrake-installLDSHARED.txt](https://github.com/firedrakeproject/firedrake/files/402087/firedrake-installLDSHARED.txt)

**Comment by CamillaBressan** [comment]
And in the second case:
[firedrake-installnoLDSHARED.txt](https://github.com/firedrakeproject/firedrake/files/402205/firedrake-installnoLDSHARED.txt)

**Comment by dham** [comment]
OK, The noLDSHARED file sheds some light on what is going on: 

```
libtool: link: gcc -dynamiclib  -o .libs/libspatialindex.4.dylib   -Wl,-force_load,src/spatialindex/.libs/liblibrary.a -Wl,-force_load,src/storagemanager/.libs/libstoragemanager.a -Wl,-force_load,src/rtree/.libs/librtree.a -Wl,-force_load,src/mvrtree/.libs/libmvrtree.a -Wl,-force_load,src/tprtree/.libs/libtprtree.a -Wl,-force_load,src/tools/.libs/libtools.a  /usr/local/lib/libstdc++.dylib -L/Users/admin/Downloads/build/x86_64-apple-darwin14.0.0/libstdc++-v3/src -L/Users/admin/Downloads/build/x86_64-apple-darwin14.0.0/libstdc++-v3/src/.libs -L/Users/admin/Downloads/build/x86_64-apple-darwin14.0.0/libstdc++-v3/libsupc++/.libs -lm -lpthread    -install_name  /Users/camillabressan/firedrake/lib/libspatialindex.4.dylib -compatibility_version 5 -current_version 5.1 -Wl,-single_module
ld: warning: directory not found for option '-L/Users/admin/Downloads/build/x86_64-apple-darwin14.0.0/libstdc++-v3/src'
ld: warning: directory not found for option '-L/Users/admin/Downloads/build/x86_64-apple-darwin14.0.0/libstdc++-v3/src/.libs'
ld: warning: directory not found for option '-L/Users/admin/Downloads/build/x86_64-apple-darwin14.0.0/libstdc++-v3/libsupc++/.libs'
```

To me this looks like gcc was at some point installed in/from `Users/admin/Downloads/`. The build isn't there any more but the binaries are still installed somewhere and are looking for those libraries. They don't find them and therefore linking fails for every single symbol in the c++ std: namespace.

I think we need to try to work out how much this old gcc is polluting your compile stack. For example, for me, `which gcc` produces `/usr/bin/gcc` and `gcc --version` indicates that this is really `clang v7.3.0`. Similar results occur for `g++`. What do you find for these entries?

As an aside, I notice from your very first posted logfile that your xcode is out of date (6.1 vs current 7.3). I'm not sure if this is related or not but upgrading can't hurt.

The log you provided with LDSHARED set appears to successfully bypass the old gcc but it's failing on  unresolved symbols. After doing some googling, I *think* this is due to a missing option. Could you try setting LDSHARED to `clang -bundle` and see if that is better?

Sorry for the inconvenience.

**Comment by CamillaBressan** [comment]
Hello again,

So I took the chance to remove the old binaries and to do an upgrade to the El Capitan Mac version. Having the most recent version of Xcode and using the homebrew packages for gcc, open-mpi and python solved the issues, without setting any environment variable.
The build was successful and firedrake runs normally.

Thanks a lot for your help!

**Comment by dham** [comment]
Excellent. Very glad to hear it. Incidentally you are now running essentially the setup that most of the core developers have on our laptops so that's a very tested setup which hopefully should work and upgrade reliably.
