### ISSUE TITLE
Old versions of virtualenv can cause installs to misbehave

### ISSUE THREAD

**Issue by nickaj** [firedrakeproject/firedrake#933]
If using an old version of virtualenv, the version of setuptools & pip it installs inside the environment are somewhat elderly. For example, virtualenv 1.9 installs setuptools 0.6c11 and pip 1.3.

Our current script doesn't update pip correctly inside the virtualenv (we call update before activating) and doesn't explicitly update setuptools at all.

We now depend on pip supporting the `--no-binary` option and somewhere in the dependency resolution pip attempts to remove setuptools 0.6c11 twice resulting in a failure.

Commit d233df1 fails, for example. See attached verbose log
[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/571406/firedrake-install.log.txt)

**Comment by wence-** [comment]
So I think, if I read things correctly, that the `run_pip_install(["-U", "pip"])` line on around line 1100 in firedrake-install does install into the virtualenv (because it uses the pip from the newly created virtualenv, even though it's not yet activated).  But I agree it always attempts to pass `--no-binary`.

Do things work if you replace with:

```python
run_pip(["install", "-U", "pip"])
run_pip(["install", "-U", "setuptools"])
```
?

**Comment by nickaj** [comment]
I had to reverse the order, but yes, this suffices. I will do an MR.
