### ISSUE TITLE
Spectral elements not wired for quadrilaterals

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#943]
One can now use GLL and GL elements on intervals, or compose them to get the tensor product element for interval x interval cells. However, since tensor product elements are not accepted on quadrilaterals, there is currently no way to define a GLL x GLL or GL x GL element on a quadrilateral.

**Comment by miklos1** [comment]
@dham: We discussed this yesterday at the meeting, and @wence- suggested that Q/DQ should simply mean QGLL/QGL, which in turn means that Lagrange UFL elements on intervals are to be translated to GLL FIAT elements, while Discontinuous Lagrange UFL elements on intervals are to be translated to GL FIAT elements. I'll prepare a patch for this.

**Comment by wence-** [comment]
So the reason this change breaks injection for multigrid is the following. AIUI, for state restriction, I want to exactly represent low frequencies, and alias at full amplitude high frequencies.  My polynomial interpolation-fu is weak, but it turns out, I think that for the equispaced lagrange points, just dropping the values of the nodes from the points that don't match is TRT.  For non-equispaced points, it is not.  I just, I think, need to do the straight polynomial interpolation.
