### ISSUE TITLE
collect_loops misses the zeroing of globals

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#946]
The issue with R space in SNES is that the Global which models the R component of the mixed dat does not get zeroed on second and subsequent residual evaluations (plausibly also not the first time but this does not matter as it defaults to 0). 

I *think* this is because Global.zero() does not create a ParLoop (and indeed I'm not sure it *can* create a ParLoop). This non-existent loop is therefore not collected and so does not show up in the trace of things to be executed each time.

**Comment by wence-** [comment]
I can't debug this, because a bunch of the changes you made (to add matmulttranspose and friends to the global matrices) are not available.  You probably also want to push the fixes we made to petsc4py upstream.

So what happens is that when collecting loops we collect:

```
tensor.zero
any_par_loops
```

For the mixed dat, tensor.zero just loops over the contained things and calls zero on them.

For the Dat part, this enqueues a zero loop (lazy), for the global, it immediately zeros the data (immediately).  This implementation is actually, I think, a bug in the way globals are handled: that zeroing should at the very least force evaluation of any trace that depends on this data (as happens for Mat.zero in petsc_base.py).  However, perhaps a better way to do this is just queue up a lazy computation that does the zeroing, e.g.:

```python
class ZeroGlobal(LazyComputation):
    def __init__(self, global_):
        super(ZeroGlobal, self).__init__(reads=[], writes=[global_], incs=[])
        self.global_ = global_

   def _run(self):
      self.global_.data[...] = 0
```


And then implement global.zero as:

```python
class Global(...);

    def zero(self):
        ZeroGlobal(self).enqueue()
```

**Comment by wence-** [comment]
Untested, obviously.

**Comment by wence-** [comment]
That wasn't it, but I have a fix, will push now.

**Comment by wence-** [comment]
Appears to be fixed by latest changes in pyop2 globals_petsc branch.  That also fixes a number of long-running bugs that we just fortunately hadn't noticed.
